lua/neogit/lib/git/status.lua

If the branch was not yet pushed, tokens[2] is nil and vim.split breaks

Fix error when branch is only local

---

lua/neogit/status.lua

tl;dr: I want splits :)
With this change, a user can set the way in which the status buffer will
open by using the lua invocation directly like so:
`require'neogit.status'.create('split')`
Defaults to 'tab' to preserve old behavior. No argument sanitization, but it's also undocumented, so eh. Not sure if we should add a specific command like `SNeogit` or just document the lua api.

Allow configuration of buffer kind

---

lua/neogit/lib/git/status.lua
lua/neogit/status.lua
syntax/NeogitStatus.vim

Adds the commit message of the current commit of head and upstream to the status buffer and only displays upstream when there's actually an upstream configured.
Had to switch highlighting of the head and upstream lines to the highlighting api, because I don't know how to do the current highlighting with :syntax. The highlights may need to be cleaned up on refresh, but I wasn't able to actually refresh an open status buffer with a changed branch and I didn't want to implement blind.

Display improvements to status buffer overview

---

README.md
ftplugin/NeogitStatus.vim
lua/neogit/lib/buffer.lua
lua/neogit/status.lua
syntax/NeogitStatus.vim

There's a lot rough edges on this one, but I wanted your opinion on if you even want to take the UI in that direction, so here's a pull request :smile: 
The changes come in 2 parts:
1. I refactored how file diffs are rendered to the buffer, so I can better keep hunk location data in the locations table. I suppose this worsens performance on the refresh somewhat, but it's easier to keep the locations table up-to-date like that. If it *is* a problem, I'm happy to optimize that.
2. I used the aforementioned location data to get the current smallest section under the cursor, then used `signs` to highlight that region. This gives the same context highlighting that magit implements. As a next step, using the same data to contextually move the cursor to the next section/hunk should be trivial. …

WIP: Contextual section highlighting

---

README.md
lua/neogit/lib/git.lua
lua/neogit/status.lua

Add a new command `x` that will discard changes under the cursor,
after user confirmation. Works on hunks, unstaged and staged files.
Does not currently work on untracked files due to a bug in hunk
detection firing on those.
Does not currently work on whole sections or selections.

Add shortcut to discard changes

---

Makefile
README.md
tests/minimal-init.nvim
tests/poc_spec.lua

Closes #32 
Setup unit tests using `plenary.nvim`'s test harness. Plenary is
expected to be installed as a plugin on the neovim instance you're
running your tests on.
I opted out of adding plenary to the repository since git plugins are usually directly pulled from repositories and including plenary into that seems wrong. So I just expected it to be installed already.
I included a small sample test suite to show what's possible, but no actually meaningful tests yet.

test: PoC Unit Test setup

---

doc/neogit.txt

Every plugin should have help tags. I don't think it's a good idea, in the long run, to have everything in the README. I started the documentation which is heavily inspired by  Tim Pope's fugitive, hopefully, that's ok.

Add documentation to the project with vim's :help

---

lua/neogit/lib/buffer.lua

The `:bufdo` command can only operate on listed buffers. Since we use that
to target the status buffer to create folds, we need to make sure that
buffer is listed.
Closes #43

fix(#43): set content_buffer for floating status as listed

---

lua/neogit/async/uv.lua
lua/neogit/lib/git.lua
lua/neogit/lib/git/cli.lua
lua/neogit/lib/git/log.lua
lua/neogit/lib/git/status.lua
lua/neogit/lib/util.lua
lua/neogit/popups/commit.lua
lua/neogit/popups/log.lua
lua/neogit/popups/pull.lua
lua/neogit/popups/push.lua
lua/neogit/status.lua

Closes #23 
This is from my master branch though, so there's quite a bit more in the MR:
- there's a new way to build and call git commands via a builder pattern. I found the existing way a bit cumbersome and metatables are fun, so here we are :D
- added some of the missing commands for commit and log popups that were easy to add.
- replicated the pull/push commands to both p and u. Since we currently do not have the distinction implemented (and do we even want to?), having one of them do nothing is just confusing.
Regarding #23, I've changed the file we use to store the commit message in. The primary reason is that git manages the `COMMIT_EDITMSG` file itself and that conflicted with the file handling I implemented. We now read the content of the commit message file when opening the …

Keep commit message on commit failure and more

---

README.md
lua/neogit/lib/git/cli.lua
lua/neogit/lib/git/stash.lua
lua/neogit/lib/popup/lib.lua
lua/neogit/popups/stash.lua
lua/neogit/process.lua
lua/neogit/status.lua

Stash control. This PR implements stashing everything or just the index, as well as popping, applying or dropping a highlighted stash.
Things to note:
- I chose `Z` for the popup, since `z` is used for folds in vim. Any other key would make just as much sense I guess, I'm just not very creative :sweat_smile: 
- The logic for staging the index only is lifted straight from magit. It *should* support also stashing the worktree, however I had no success with that, so I fell back to just using `git stash` for that. Executing the git commands manually though gives the correct result, so I'm not even sure what's the problem. Any hint would be much appreciated, since this issue is also what prevents me from implementing the `--untracked` flag.
- Trying to apply (or drop/pop) a stash while not …

Stash popup

---

lua/neogit/lib/popup/lib.lua

This PR fixes #74, by checking whether or not the action being rendered has a neighbour or not and if not padding it or not. I've tested this in most of the buffers and don't think it broke anything. Also wasn't sure of the rules re formatting but I've indented some long lines with the extra conditionals

Remove extra padding from buffer actions

---

colors/neogit.vim
lua/neogit.lua
lua/neogit/lib/notification.lua
syntax/NeogitNotification.vim

Closes #79 
Doing this one as a PR because I'm not entirely sure this is the right way to do this either. The highlights could just as well go into a `ftplugin`-file or just into our `neogit.vim`. I'm confused :sweat_smile:

chore: move notification hl to syntax-file

---

README.md
lua/neogit/config.lua
lua/neogit/popups/commit.lua

Open for discussion: I'm not sure whether this is something that would be useful to other people (and hence belongs in this plugin) or not. I personally find it a bit burdensome (and takes me out of my flow) since I'm used to typing my message, hitting "ZZ" and then moving on.
This is also my first time writing Lua so if there's a better way to format this conditional, please let me know.

Add option to disable commit confirmation prompt

---

lua/neogit/integrations/diffview.lua

Neogit's file struct items don't always have stats attached to them (for instance for deleted files), in which case an error is thrown when trying to open diffview.

fix(diffview): Handle files without stats correctly.

---

lua/neogit/lib/buffer.lua

This is small changed. This onlt make neogit preserve last `winhl` when creating buffer

Make Neogit work with tokyonight.nvim

---

README.md
lua/neogit/buffers/commit_view/init.lua
lua/neogit/config.lua
lua/neogit/lib/git/cli.lua
lua/neogit/lib/notification.lua
lua/neogit/lib/popup.lua
lua/neogit/lib/util.lua
lua/neogit/popups/commit.lua

I replaced all notifications with `vim.notify`. All messages will be displayed in echo area by default, but users can simply override this function to have nice notifications as they want or use a dedicated plugin, such as https://github.com/rcarriga/nvim-notify
In theory you can also use `vim.log.levels.TRACE` for debugging.
Closes #193

Use vim.notify

---

README.md
lua/neogit/config.lua
lua/neogit/popups/commit.lua

Hey! 
First off, love the plugin, appreciate all the work you've done.
One thing I missed from Magit was, once the commit popup appeared, you could begin typing immediately instead of switching into insert mode and then typing.
I added a configuration option to allow for that behavior, while keeping the default. 
The naming is kind of awkward since I was trying to stick with the other vars you had but let me know if you'd like me to switch to something like "enable_insert_on_commit" instead of the negative.
Thanks again!

Add Insert on commit configuration

---

lua/neogit/lib/git/branch.lua
lua/neogit/lib/git/cli.lua

As I mentioned in #239, the current approach makes some false assumptions about valid formatting for remote- and branch names. A regex won't be enough to separate these when they're presented together because there's no unique separator between them. I think the most straight forward approach is to just read the branch's remote from the git config.

fix: Parsing of upstream remote + branch.

---

lua/neogit/lib/job.lua

The last line in a job channel callback may be a partial line. Until now this has just been ignored. Seemingly, this works fine most of the time, but I had a commit view consistently fail to parse `git-show` output because several characters were dropped from the beginning of a line.
From `:h channel-callback`:
```vimhelp
{data}	    Raw data (|readfile()|-style list of strings) read from
the channel. EOF is a single-item list: `['']`. First and
last items may be partial lines! |channel-lines|
```

fix: Account for partial lines in job output.

---

lua/neogit/popups/commit.lua

The issue is when we do `ca`, the pop up git message appends git message template. This contradicts the behavior from `git commit --amend`, which just use the previous git message without appending anything.

Fix git commit amend appending unnecessary template

---

lua/neogit/status.lua

previously get_current_hunk_of_item would fail if the file was not tracked
by git. The reason was that get_current_hunk_of_item calls
get_hunk_of_item_for_line, which loops over ipairs(item.hunks), which
will fail if item.hunks is nil.
An important consequence of this is that going to a specific file in the
status would fail if the file was not tracked by git (for instance, it's
a new file we're adding to the repo now). The code to go to a file is
calling get_current_hunk_of_item to find out which line to go to in the
file.

get_current_hunk_of_item returns nil if the item is not tracked by git

---

README.md
lua/neogit.lua
lua/neogit/config.lua
lua/neogit/popups/help.lua
lua/neogit/status.lua

Addresses #244 
Changes of this PR:
- using magit keybindings can be done directly through the `setup` function with `use_magit_keybindings = true`
- `false` by default
- unbind `p` in magit keybindings, used to be "push" but `P` does the same thing and this is more magit-like
- help popup now shows correct keybindings by inspecting `config.values.use_magit_keybindings`
- documentation changes
I welcome any changes/comments to this PR.
P.S. for backward compatibility, I still keep the `config.use_magit_keybindings()` function. I can remove it if you want.

fix: update help popup according to user config

---

README.md
lua/neogit.lua
lua/neogit/status.lua
plugin/neogit.vim

Resolves an issue where, if we're in a large repo, dirvish will refresh Neogit aggressively. For me, this causes memory to go out of control because of `git ls-files` being run on a large repo over and over

fix: short circuit refresh on dirvish

---

lua/neogit.lua

The open function still overrides the default kind option from the setup.

remove default kind "tab" in open function

---

lua/neogit/status.lua

the git status file discard code assumed that the vim current folder was set to the git repository root, which is not necessarily the case. This fixes it.

fix file discard path

---

lua/neogit/lib/buffer.lua

This greatly simplifies the floating window creation system.
This also relies more on the colorscheme definition for consistency,
and avoids random calls to `vim.wo`.

refactor(floating): use builtin border system

---

lua/neogit/integrations/diffview.lua
lua/neogit/status.lua

**Description :**
As described in issue #286, when you press `d` to open diffview on commit or stash it doesn't work and display an error.
**FIx :**
This PR adds support for opening of diffview for commit and stash.
It compares the section and try to extract the commit id or stash id.
If the cursor is in `recent` or `unmerged` section it extracts the commit id, if the cursor is in `stashes` section it extracts the stash id.
In all other cases, it reverts to the original behavior.

fix(#286): add diffview support for commit & stash

---

lua/neogit.lua

When the user types some command that does not have a popup associated with it, Neogit throws an error. It fixes #278.

Handles non-existent commands.

---

lua/neogit/lib/git/cli.lua
lua/neogit/lib/git/diff.lua
lua/neogit/lib/git/stash.lua

Pressing tab on a file in the NeogitStatus popus would turn the arrow,
as if was open, but wouldn't show the diff. This happened when I
configured git diff to use an external diff tool like below
```
git config --global diff.external difft
```
This change disables external diffs in the status buffer

Fixed diffs when diff.external is set to something that cannot be parsed

---

lua/neogit/lib/git/cli.lua

From `man git(1)`:
```
--no-optional-locks
Do not perform optional operations that require locks. This is
equivalent to setting the GIT_OPTIONAL_LOCKS to 0.
[...]
GIT_OPTIONAL_LOCKS
If set to 0, Git will complete any requested operation without
performing any optional sub-operations that require taking a lock.
For example, this will prevent git status from refreshing the index
as a side effect. This is useful for processes running in the
background which do not want to cause lock contention with other
operations on the repository. Defaults to 1.
```
And from `man git-status(1)`:
```
BACKGROUND REFRESH
By default, git status will automatically refresh the index, updating
the cached stat information from the working tree and writing out the
result. Writing out the updated index is an …
```

fix(cli): Use `--no-optional-locks`.

---

lua/neogit/lib/buffer.lua
lua/neogit/status.lua

- Avoids the "Already only one window" message that appears when you close a neogit tabpage, and there's only one window in the tabpage.
- Avoids errors when closing a neogit tabpage and it's the last tabpage.
- Avoids errors when closing a neogit tabpage, `'hidden'` is disabled and there are buffers with unsaved changes open in the tabpage.
- Avoids unnecessary writes on GoToFile (only write the current file if `'hidden'` is disabled and it's a normal, writeable buffer).

fix(status): Adjustments to 'Close' and 'GoToFile'.

---

lua/neogit/buffers/branch_select_view/init.lua
lua/neogit/buffers/branch_select_view/ui.lua
lua/neogit/lib/git/branch.lua
lua/neogit/lib/git/cli.lua
lua/neogit/popups/branch.lua

Added an interactive list to select branches.

feat(branch): added interactive list to select branches

---

lua/neogit/lib/git/status.lua

we currently don't display unmerged files (eg conflicted files) in git status. this fixes it.

status: also display unmerged files

---

lua/neogit/buffers/commit_view/parsing.lua
lua/neogit/buffers/common.lua
lua/neogit/lib/git/diff.lua
syntax/NeogitCommitView.vim

Parse diffs for renamed files in the commit view correctly.
I also added a highlight for the diff headers in the commit view (just `gui=bold`), as I felt that they blended in with the rest of the text.
<p>
<details>
<summary><b>Comparison with Magit:</b></summary>
| Neogit | Magit |
| --- | ----------- |
| <img src="https://user-images.githubusercontent.com/2786478/179023245-03868cdc-23e5-494a-86c4-684ab5ff0cec.png" width="450em"/> | <img src="https://user-images.githubusercontent.com/2786478/179026922-18081cd8-7aff-4b5e-9ab4-8ed85cb02e91.png" width="450em"/> |
</details>
</p>

feat(commit_view): Parse diffs for renamed files.

---

README.md
lua/neogit/config.lua
lua/neogit/lib/popup.lua

`popups.kind` is a new config option in a similar vain to `kind` and `commit_popup.kind`.
This is the MR for https://github.com/TimUntersberger/neogit/issues/315
So with these settings
```
require("neogit").setup({
popup = {
kind = "vsplit",
},
...
```
and pressing `c` in the neogit view I get this result:

Make kind for all popups configurrable via config

---

ftplugin/NeogitRebaseTodo.vim
lua/neogit/buffers/commit_editor/init.lua
lua/neogit/buffers/commit_select_view/init.lua
lua/neogit/buffers/commit_select_view/ui.lua
lua/neogit/buffers/rebase_editor/init.lua
lua/neogit/client.lua
lua/neogit/editor.lua
lua/neogit/lib/git/cli.lua
lua/neogit/lib/git/rebase.lua
lua/neogit/lib/job.lua
lua/neogit/lib/rpc.lua
lua/neogit/popups/commit.lua
lua/neogit/popups/rebase.lua
syntax/NeogitRebaseTodo.vim

adds the possibility to perform interactive rebase

feat: added rebase interactive

---

lua/neogit/buffers/log_view/init.lua
lua/neogit/integrations/diffview.lua

Description :
This PR add a mapping `d` in LogView to open diffview.nvim with the diff of the commit under the cursor.

feat: add diffview support for log view

---

lua/neogit/integrations/diffview.lua

The `<SHA>^..<SHA>` format is unnecessarily verbose and doesn't work if
`<SHA>` has no parent commit. The `<REV>^!` format more accurately
describes the range of a single commit, and works regardless of the
number of parents.

fix(diffview): Use the `^!` notation to describe single-commit ranges.

---

lua/neogit/lib/popup.lua

Hi, and thanks everyone for awesome work on this plugin!
I recently started playing with it, and first thing I noticed is that it took me some time to figure out that popup should be closed with `q`. I think having `<esc>` as an option would be more convenient.

Close popups with <esc>

---

.github/workflows/lint.yml

1.0.0 is broken and is causing the pipeline to fail.
This PR fixes back the pipeline.

chore: update stylua-action version

---

lua/neogit/lib/git/diff.lua

Was causing #360. This should at least get rid of the error.

fix: check diff header length before parsing

---

lua/neogit/buffers/commit_editor/init.lua
lua/neogit/buffers/rebase_editor/init.lua
lua/neogit/integrations/diffview.lua
lua/neogit/popups/commit.lua
lua/neogit/popups/push.lua
lua/neogit/status.lua

The double quote pattern is already dominant in the repo. This commit makes it uniform.
Keeping the multi brackets would come in handy for complex multiline commands or those in need of escape characters. 
But neither is the case here.

chore: use uniform vim.cmd formatting

---

lua/neogit/process.lua

Without this patch git is unable to contact the ssh agent for commit singing with an ssh key.

Pass SSH agent related env vars to client processes

---

README.md
lua/neogit/popups/pull.lua

refs #105
This event is useful to me as it allows me to automatically trigger a recompile of my codebase whenever new code was pulled.

Added NeogitPullComplete event

---

lua/neogit/lib/buffer.lua

Before I was not able to remove default mapping from `q`
```lua
local neogit = require("neogit")
neogit.setup {
mappings = {
status = {
["q"] = "",
}
}
}
```
After this PR `q` will work the same (by default), but remapping `q` to `""` will also work.
For example, I use `q` for [Leap](https://github.com/ggandor/leap.nvim).
To force leap working inside neogit buffer I have to write autocomand around "NeogitStatusRefreshed".
Now I am able to just use the config above.

Remove hardcoded `q` for exit (to simplify having custom `q` mappings)

---

lua/neogit/status.lua

fix: avoid error message in non-git directories

---

lua/neogit/integrations/diffview.lua

Hello @TimUntersberger! I hope you're doing well.
We're working on some [big changes in diffview](https://github.com/sindrets/diffview.nvim/pull/235) in preparation of implementing support for multiple VCS. This PR brings some small adjustments that will be necessary for the diffview integration in Neogit to work after we have merged that refactor.
This also enables diffviews created from Neogit to use the merge-tool in Diffview.nvim. (A note on that: it seems like merge conflicts in Neogit shows up in the "Untracked" section. This seems unintentional, no?)
I'll remove the draft status of this PR once we merge the changes on our end :)

feat: Update diffview integration.

---

README.md
lua/neogit/config.lua
lua/neogit/process.lua

Ended up resolving #445 by myself. Basically, I added a new configuration option preview_buffer.kind which will allow the user to select what kind of buffer the preview_buffer/NeogitConsole renders as. While doing this I also resolved an issue where if the preview_buffer as a floating window was unfocused it could not be re-focused again after it loses focus.

Added the ability to set the kind of buffer used for preview_buffer.

---

lua/neogit/status.lua

This is a fairly small change, the effect of which is to vertically align filepaths in the status window:
Compare that with how it is now:
Much more readable!
(ignore the colors - thats just some fun I'm having)

Make all file modes equal length in Status

---

README.md
lua/neogit/config.lua
lua/neogit/lib/git/branch.lua
lua/neogit/lib/git/cli.lua

When I checkout, I want to see branches sorted by commit date. 
This change allows user to specify their own sort settings.
Flag description: https://git-scm.com/docs/git-branch#Documentation/git-branch.txt---sortltkeygt
Sorting keys: https://git-scm.com/docs/git-for-each-ref#_options
#144 #392

Add custom option that allows to sort branches

---

lua/neogit/lib/git/diff.lua

I did some profiling for the general sluggishness when a very large file is present in the index, and it came up that `parse_diff()` was the culprit. From there, I started teasing the different functions out of that larger one to find where the problem came from, and low-and-behold, it was building hunks.
So, with some metatable magic, we can defer computing the hunks until somebody tries to actually _render_ it. That way, if you are just doing some staging/committing with the folds closed, you never pay for something that you never see.
I did change a couple things beyond that, though:
1. `parse_diff()` took a second argument, `with_stats`, but I couldn't find a single caller who actually passed that argument. So, it's removed.
2. Replacing calls to `vim.startswith("...")` with …

Refactor diff.lua to speed up large files in index

---

lua/neogit/client.lua

This PR is fixes issue #424
There was only two issues, and all of them in `lua/neogit/client.lua`
First one is: wrong quotes in `neogit.client.get_nvim_remote_editor()` at line 12. This caused neovim command look like this: `-c "lua require(""neogit.client"").client()` (note extra quotes around `neogit.client`)
Second issue is in `neogit.client.client()`. In `file_target` and `client` variables was unescaped reversed slashes `\`. 
P.S. Sorry for bad English 😅

Fixed issue with remote client on Windows

---

lua/neogit/lib/popup.lua
lua/neogit/lib/popup/builder.lua

I thought it would be easier for these to stand in their own PR.
`popup`
- Rename `option.parse` to `option.internal` (parse made no sense)
- Add `arg.cli_prefix` since some git flags do not use `--`. Some use `++`. Some use a single `-`. It's wild.
- Add `config` type to popups. This is, you guessed it, a `git config` setting the user can change.
- Switches can now be incompatible with other switches (defined in the popup creator) to prevent invalid input states
- `option`s can now support a `choices` table, to restrict the user to a set of valid inputs
- Adds a 'heading' value to allow for different categories of actions
`builder`
- Combine `self.state.switches` and `self.state.options` to `self.state.args` so we have better control over placement and ordering, and can set more detailed …

Upstreaming 3/n - Popup/Builder libs

---

README.md
lua/neogit.lua
lua/neogit/lib/git/cli.lua

Neogit has now moved to an organization to ensure the longevity of this project and make it more accessible for maintainers.
This PR notifies users who are still on the `TimUnterberger/neogit` remote using neogits own api, and is consequently most  likely the best example of *dog fooding* I've encountered

feat! move neogit to https://github.com/NeogitOrg/neogit

---

lua/neogit/buffers/commit_view/init.lua
lua/neogit/buffers/log_view/init.lua
lua/neogit/buffers/reflog_view/init.lua
lua/neogit/popups/revert/actions.lua
lua/neogit/popups/revert/init.lua
lua/neogit/status.lua

Extracted from: https://github.com/CKolkey/neogit/pull/44

Add revert popup to commit view, and align API with cherry pick popup

---

lua/neogit/lib/git/cli.lua

Currently the git root will not be correctly detected within symlinked directores not containing a `.git` directory within its upper paths. This PR resolves that issue by relying entirely upon `git rev-parse`. The commit 3149cd6fda556c9022b3e9dd03aee85a854be478 was created to remove "noisy output" when `git rev-parse` failed. This PR also resolves that issue by checking the return code emitted by `git rev-parse`.
See #575 for more details.
If this PR is not desired, feel free to close it out :smile:.
Closes #575

fix: correctly detect the git root location

---

.github/workflows/lint.yml

This speeds up the Selene job in the lint action significantly when the cache is valid. Selene's last update was 4 months ago so there's really no need to be installing it on every run. Much faster to use a cache.
Take a look at [this run](https://github.com/treatybreaker/neogit/actions/runs/5556895200/jobs/10149993953) to see the speed up. It only took the Selene job ~9 seconds to complete with the cache.

ci: cache selene install

---

tests/git_cli_spec.lua
tests/git_harness.lua

This commit also allows the `in_prepared_repo` harness to pass its directory to the function it wraps, which is necessary to check the root directory.
This helps with validation and checks of the git root directory, should help with avoiding the problem that cropped up in #575.

test: add tests for git root detection

---

lua/neogit/process.lua

Prior to this commit the process module would spawn a Neovim terminal in the background immediately and write whatever data it needed to. This interferes with user auto commands for `TermOpen`. See #587 for an example.
This commit defers opening the terminal until absolutely necessary and writes all the data to it at that point. This ensures relevant auto commands for `TermOpen` are properly issued when the term is going to be actually used, not when its been backgrounded.
Another thing this commit does is improve the scroll function to use in-built functionality from Neovim instead of parsing the terminal buffer. By going into insert mode, waiting a small amount of time, and then exiting it ensures the cursor is directly at the end of viewable content.
Closes #587

Defer entering data into console until absolutely necessary

---

lua/neogit/popups/help/actions.lua

Prior to this commit the reverse lookup done was directly modifying the `neogit.config.values.mappings.status` table which is not desired leaving status command names mapped (see `nmap Goto` for instance). We really want to modify a *copied* value to use later within the code to avoid mapping those commands. That is what this PR does.
See #561 for more details.
Closes #561

fix: do not directly modify the mapping config, use a copied value

---

lua/neogit/lib/popup.lua

Prior to this commit any floating windows that lost focus were not closed and covered the editor as well as being inaccessible in that state.
This commit ensures the window is properly cleaned up when it loses focus. This only applies to *floating* windows.
See #591 for more details.
Closes #591

fix: ensure floating popup windows are auto closed when they lose focus

---

lua/neogit/process.lua

These tend to be a bit noisy when reading logs, so lower it from debug to trace

Change log level for process

---

lua/neogit.lua
lua/neogit/autocmds.lua
lua/neogit/lib/buffer.lua

Prior to this PR using `vim.api.nvim_get_autocmds({ group = "Neogit" })` would only return the initial `setup` autocmds that Neogit created. It did *not* return the autocmds created for the buffers that Neogit created.
This PR enables users to get all the autocmds that Neogit creates. It does this by exporting the augroup in `autocmds.lua` and then importing it in `buffer.lua` so they share the same augroup.
Something to note, we may want to create a different `augroup` for the Neogit buffers in `buffer.lua` instead of using the same `augroup` in `autocmds.lua`, though it may make it a bit more difficult to search for.

fix: ensure all created autocmds are part of the Neogit augroup

---

lua/neogit/config.lua
lua/neogit/popups/help/actions.lua
lua/neogit/status.lua

Prior to this PR the top hint the status buffer was hardcoded to show certain keys.
This PR checks the keymap and inserts the correct key for the top hints, unfortunately this does impact the way the keys look in the hint:
This PR also adds a function `get_reversed_status_map` to `config.lua` and uses that for the reversed mapping lookup.
Fixes #564 (partially)

fix: show the correctly bound key for the top Status Hint

---

CONTRIBUTING.md

feat: `CONTRIBUTING.md`

---

lua/neogit/integrations/diffview.lua

fix: make neogit respect user's configuration of diffview

---

lua/neogit/buffers/commit_editor/init.lua
lua/neogit/lib/buffer.lua

Prior to this commit hitting `q` in normal mode in the commit editor would close it even if the text had not been saved. Also, prior to this commit, the `Buffer:get_option` in `lib/buffer.lua` never actually returned the option value :sweat_smile:. 
This PR pops up a warning when `q` is hit in normal mode and the buffer has unsaved modifications, we may want to change the message and the log level. 
Currently the message is: 
> Commit message has not been saved! Try `:w`.
and the log level is set to `WARN`.
This PR also fixes the `Buffer:get_option` to *actually* return the value it got.
Let me know if any changes are desired to the message or log level, and secondly I have a question. Do y'all prefer me to force push or to create a separate commit for each change? Usually I try to avoid …

feat: do not close commit message with `q` until saved

---

lua/neogit/popups/branch/init.lua
lua/neogit/popups/branch_config/init.lua
lua/neogit/popups/pull/init.lua
lua/neogit/popups/push/init.lua
lua/neogit/popups/rebase/init.lua

This makes popups that were being called by `require("neogit.popups").call("POPUP_HERE")()` work correctly prior to the Neogit status being opened.
This PR will cause an early return when neither a head branch or a current branch is detected to avoid any errors.
Fixes #639

fix: properly access the current git branch via an accessor

---

lua/neogit/lib/buffer.lua

String concatenation is expensive in LUA since all strings are interned, so they need to be rehashed every single time it's mutated. String.format + table.concat is a better way to do this.

Perf: use string.format for a minor performance gain

---

lua/neogit/buffers/commit_editor/init.lua
lua/neogit/lib/buffer.lua
lua/neogit/lib/ui/init.lua

Speed-up redrawing by using buffers for lines/highlights/signs/extmarks and only flush buffers once. Test this by opening the `LogView` and toggling open and closed a commit (via `<tab>`). On master... slow. On this branch, faster.
before:
after:
I'm not sure if I can get the `add_highlight` call to be any faster, but thats the next thing to try.

Perf: Speed-up buffer updates

---

doc/neogit.txt
lua/neogit/config.lua
plugin/neogit.lua

Add pull popup flag '--rebase' to ignored settings. This value is handled by a config value, so shouldn't be persisted.
If you experience issues, use `:NeogitResetState` to fix it.

Breaking: Update default ignored flags

---

lua/neogit/lib/finder.lua

after closing the telescope prompt, the focus wouldn't go back to the neogit buffer if it was open as a split.
This ensures that the status buffer is refocused just before the on_select function is called. If on_select() opens a new popup, then the popup is correctly split from the status buffer.
Fixes #689

Bugfix: after closing the telescope prompt, the focus wouldn't go back

---

lua/neogit.lua

This is done to ensure the `cwd` is updated for the status buffer.
1. This ensures that Neogit uses the updated cwd when passed the `cwd` flag
2. This ensures that Neogit *always* gets a cwd via the `open` command
Closes #668

fix: always open new status buffer for `open` command

---

lua/neogit.lua
lua/neogit/config.lua

Follow up for #631 
This adds annotations for the Neogit config and applies them for the `setup` function.
This makes it *much* easier to configure Neogit within Neovim for users of the [Lua Language Server](https://github.com/LuaLS/lua-language-server)
See below for a quick demo:
https://github.com/NeogitOrg/neogit/assets/58627896/4cd9a0f4-b53e-4701-8ee8-c16326bd73c8

feat: add annotations for the Neogit config

---

lua/neogit/lib/git/cli.lua

In my case `/bin/bash` was spitting a warning message, which caused the string equality check to fail. It should be more robust to check for an exit code of 0 instead.

fix: use error code from `git rev-parse --is-inside-work-tree` to check if inside git directory

---

lua/neogit/lib/buffer.lua

`signcolumn` may be set to `no` and there is no way to set it to yes only in Neogit.
So Neogit may set its own sign value when the user does not disable it.

fix: if signs are not disabled, avoid overrided by user settings

---

doc/neogit.txt
lua/neogit/buffers/commit_select_view/init.lua
lua/neogit/buffers/log_view/init.lua
lua/neogit/buffers/reflog_view/init.lua
lua/neogit/lib/util.lua

Also add `util.reverse` to reverse a list-like table, and ensure commits are passed to cherry-pick popup in reverse order (oldest first)

Add cherry-pick popup documentation

---

doc/neogit.txt
lua/neogit/lib/git/branch.lua
lua/neogit/lib/git/config.lua
lua/neogit/lib/popup.lua
lua/neogit/popups/fetch/actions.lua
lua/neogit/popups/fetch/init.lua
lua/neogit/popups/push/actions.lua

Add documentation for fetch popup

---

lua/neogit/buffers/log_view/init.lua
lua/neogit/buffers/reflog_view/init.lua
lua/neogit/popups/cherry_pick/actions.lua
lua/neogit/popups/init.lua
lua/neogit/popups/revert/actions.lua

wasn't working because of a type mismatch. The `commits` table was expecting commit objects, whereas we were passing strings.
Update everything to just pass strings.

Fix: Cherry picking from log buffer/reflog buffer

---

lua/neogit/popups/branch/actions.lua

Oops. Can't get `oid` of string.

fix: When over a commit, it can be checked out via branch/revisions

---

lua/neogit/lib/git/cli.lua

This fixes the error where Neogit thinks you're not inside a git repo when invoking it while nvim's CWD it set to any path with special characters in it.
Quoting the interpolated string in `string.format` does the trick.
Fixes #736

fix: fixes repo not found when special chars in cwd

---

.luarc.json
lua/neogit.lua
lua/neogit/config.lua
tests/specs/neogit/config_spec.lua

This also fixes the type definitions to allow specifying an incomplete `status = {  }`

fix: #745 allow functions in status mappings

---

lua/neogit/lib/popup/init.lua

full-size for a few MS before resizing, which is lame.

Resize before the schedule'd cmd: Loading a popup will show it at

---

lua/neogit/client.lua
lua/neogit/lib/git/rebase.lua
lua/neogit/lib/popup/builder.lua
lua/neogit/lib/popup/init.lua
lua/neogit/popups/branch/actions.lua
lua/neogit/popups/cherry_pick/actions.lua
lua/neogit/popups/fetch/actions.lua
lua/neogit/popups/merge/actions.lua
lua/neogit/popups/pull/actions.lua
lua/neogit/popups/push/actions.lua
lua/neogit/popups/rebase/actions.lua
lua/neogit/popups/remote/actions.lua
lua/neogit/popups/reset/actions.lua
lua/neogit/popups/revert/actions.lua
lua/neogit/popups/stash/actions.lua

Remove the need to call `status.refresh()` from every single action. Instead, wrap the action function and run it with `status.dispatch_refresh()` as a callback.
This is a setup step for the file watcher.

Refactor Actions

---

lua/neogit/lib/buffer.lua

When setting `signcolumns` to `yes`, the buffers with filetype `NeogitCommitMessage` and `NeogitCommitMessage` will also have 1 column in the left margin indicating a signcolumn. However, we shouldn't have signcolumns for those buffers. We only need to have signcolumns for the `NeogitStatus` buffer. Setting the option to `auto` will automatically handle the situation.

fix: set `signcolumns` to 'auto' when disable_signs is false to avoid unnecessary statuscolumn

---

lua/neogit/lib/git/status.lua

When pushing to a pushremote for a branch for the first time, this would be nil, showing an error.

Ensure there is a commit before trying to access it when refreshing status

---

README.md

Not the editable version on github.
Before: 
After:

README links to renderded CONTRIBUTING.md

---

lua/neogit/lib/popup/init.lua

Register a handler for every prefix that blocks waiting for the next key
using `getcharstr` and invokes the correct mapping

feat: infinite wait for the next key after `-`,`=`

---

README.md
lua/neogit/config.lua
lua/neogit/lib/finder.lua

Adds the basic popup integration for fzf-lua. I mapped a majority of the telescope options to the fzf-lua equivalents as to not add more custom options.
Also if both telescope and fzf-lua integrations are enabled, the telescope integration takes precedence.
Let me know if I need to fix anything or if I'm missing anything.

feat: Add basic fzf-lua integration

---

lua/neogit/lib/git/log.lua

Fixes a bug when on nvim less than 0.10 where all log commands have a duplicate `--max-count` appended to them. This is because the `vim.tbl_contains` function used on 0.10 allows for a function/predicate match while lower versions do not.

fix: Do not append duplicate `max-count` on nvim versions below 0.10

---

doc/neogit.txt
lua/neogit/buffers/common.lua
lua/neogit/lib/git/log.lua
lua/neogit/lib/hl.lua

Modifies the log view buffer to highlight the commit based on the status of the commit signature.
I tried mapping the highlight colors from magit but feel free to adjust them.
Still need to add the signature output on the commit details buffer but that one is a bit more messy as I need to record if `--show-signature` was passed in the parent BufferWindow and pass it down to the CommitDetailView to be used in `git show`. I'll work on that in another PR 🤔 .
Solves half of #784

feat: Add highlighting to commit based on signature flag

---

lua/neogit/lib/ansi.lua

Discovered a bug with ansi parsing: if there were more than 9 graph characters, it would loop back over. Bad choice to use a dictionary. Switch to stack, no problems.

Bugfix: Parse ansi colors correctly when there are more than 10 graph lines

---

lua/neogit/buffers/commit_view/init.lua
lua/neogit/buffers/commit_view/ui.lua
lua/neogit/lib/git/cli.lua
lua/neogit/lib/git/log.lua
lua/neogit/popups/log/actions.lua

Modifies log commit detail view to show the signature block when the `--show-signature` flag is passed to the log buffer. When the log commit detail view buffer is opened it will run `git verify-commit` against the hash and record the output.
It might be a bit messy but we have to record if the --show-signature flag was set, then remove the --show-signature flag from the log graph view command and the actual git log command.
Then when we open a commit log from the log list page we need to check if the --show-signature flag was set from the parent git log command and run `git verify-commit` to output the signature.
I tried just parsing the signature lines in the intial `git log` command and store it in the actual commit struct but its difficult to tell where a signature block ends with …

feat: Show signature details in commit detail view

---

doc/neogit.txt
lua/neogit/lib/git/cli.lua
lua/neogit/lib/git/repository.lua
lua/neogit/lib/git/status.lua
lua/neogit/lib/hl.lua
lua/neogit/status.lua
syntax/NeogitStatus.vim

Similar to Magit's status page this commit adds the most recent tag name to the status popup with the distance (commits) between the head and tag
Unfortunately lua's pattern matching isn't as complete as I had hoped for so there might be some cases where it fails. When it fails it will just set the tag and distance to nil making it unrendered.

feat: Show tag name and distance from head on status page

---

lua/neogit/popups/remote/actions.lua

This commit fixes a small bug where if the user escapes out of the input action the return value is an empty string and the action attempts to still add the remote.

fix: Do not continue remote action when input is empty

---

lua/neogit/buffers/commit_view/init.lua
lua/neogit/buffers/commit_view/ui.lua
lua/neogit/lib/git/log.lua
lua/neogit/status.lua
tests/specs/neogit/popups/remote_spec.lua

This commit allows users to open the commit/ref/tag under their cursor for the top 4 header lines (head,upstream,pushRemote,tags) similar to how magit allows user to do the same on the status buffer. Similarly to how magit displays commits in their viewer, the top line now shows the passed argument (commit,ref,tag) used in the git command. Then below that line is the full commit hash of it.  
Had to modify the section table a bit to allow handling sections where there are no files within but it gets the job done.
Maybe it would be a nicer api in the future to define sections with callbacks for when a user performs a select action on instead of having to check the name of the section and perform an action from there.
Like always feel free to point out changes 🙏 . Also should I be posting …

feat: Allow opening commit details from status buffer header lines

---

lua/neogit/status.lua

When there is no location stored, use the first section that isn't a header

---

lua/neogit/lib/finder.lua

This is a very simple change to prevent Telescope from caching the finder.
Currently, if you open the finder in Neogit (when checking out a branch, for example), Telescope caches the picker state after it is closed. This overwrites any previously cached picker, which is inconvenient, but more importantly it means that if you then run `:Telescope resume`, it shows the old picker a second time, and attempting to close it results in a bunch of `cannot resume dead coroutine` errors.
I am not familiar with the codebase at all, but I had a feeling it would be a one-line fix so I thought I'd make a PR myself. This change fixes the issue for me, but if something needs to change somewhere else then feel free to add to or close this PR.

Prevent Telescope finder caching

---

lua/neogit/lib/state.lua

If the value is false, and the default is true, then it'll always return the default instead.
Fixes #824

Only return default when the read value is _nil_.

---

lua/neogit/process.lua

Simple fix to check if the handle is closing by using our process instance's `stop_timer` method instead of duplicating it in the `start_timer` method.
I'm curious as to the function `Process:start_timer`, why are we only starting a timer if the current instance's timer is `nil`? Is this so we don't accidentally mess with the current timer?
Fixes #843

fix: check if the timer is closing or closed before trying to close it

---

lua/neogit/status.lua

Fixes the error when opening the branch popup in the header section

fix: nil item list when in header section

---

lua/neogit/status.lua

Fixes #857 
The real changes here are:
```lua
if h.diff_from <= last_line and h.diff_to >= first_line then
```
to
```lua
if h.first <= last_line and h.last >= first_line then
```
That fixes interacting with the correct hunk.
Then:
```lua
if partial then
from = h.diff_from + math.max(first_line - h.diff_from, 0)
to = math.min(last_line, h.diff_to)
else
``` 
to
```lua
if partial then
local cursor_offset = first_line - h.first
local length = last_line - first_line
from = h.diff_from + cursor_offset
to = from + length
else
```
Fixes visual selection's of hunks being staged/unstaged with folded sections above them.

WIP: Fixes finding the right section

---

lua/neogit/lib/finder.lua

Allows for user to input an entry NOT available in telescope, and that just works fine.

Feature: Allow user input to telescope prompt when no entries are available

---

.github/ISSUE_TEMPLATE/bug_report.yml

I guess I wasn't gone for long 😉.
This PR significantly overhauls the minimal init in the `ISSUE_TEMPLATE/bug_report.yml` file. It's mostly a heavily
modified version of [@ten3roberts minimal init](https://github.com/NeogitOrg/neogit/pull/616/#discussion_r1264732449).
Per the requirements of #621, the new minimal init does the following:
- By default the minimal init downloads:
- [Neogit](https://github.com/NeogitOrg/neogi)
- [Telescope](https://github.com/nvim-telescope/telescope.nvim)
- [Plenary](https://github.com/nvim-lua/plenary.nvim)
- [Diffview](https://github.com/sindrets/diffview.nvim)
- The minimal init does **_not_** setup any of the plugins. That's on the user to do as they may not be reporting a bug with telescope, diffview, etc.
- The new minimal init voids `packpath` and …

docs: improve minimal init

---

lua/neogit/lib/finder.lua

Fixes #872 and #863 
Can't blindly cast to table. Only return a table if multi-select was requested (consistent with fzf/telescope)

Fix: Properly return table when multiselect is enabled.

---

lua/neogit/lib/git/rev_parse.lua

Fix: When in a new repo, don't error out

---

README.md
doc/neogit.txt
lua/neogit/buffers/tag_editor.lua
lua/neogit/client.lua
lua/neogit/config.lua
lua/neogit/editor.lua
lua/neogit/lib/git.lua
lua/neogit/lib/git/cli.lua
lua/neogit/lib/git/refs.lua
lua/neogit/lib/git/tag.lua
lua/neogit/lib/input.lua
lua/neogit/lib/util.lua
lua/neogit/popups/init.lua
lua/neogit/popups/tag/actions.lua
lua/neogit/popups/tag/init.lua

This commit implements the magit tag popup.
Completed:
- Create tag
- Delete tag
Needs improvement:
- Prune
Haven't started:
- Create release
The prune implementation works but I need to call `ls-remote` asynchronously as it takes  a bit of time.
I also need to figure out how to show the user the list of local/remote tags to be pruned by selecting the y option 🤔 .
Closes #783

feat: Add Tag popup

---

lua/neogit/lib/git/cli.lua
lua/neogit/popups/rebase/actions.lua

As discussed in https://github.com/NeogitOrg/neogit/discussions/862
I really tried to write a test for this, but couldn't figure out how to wait until the `git-rebase-todo` was present to check its contents. Maybe later :)
Feedback very welcomed, as always.

feat: interactive rebase should include current commit

---

lua/neogit/status.lua

After reviewing the test and the code in [lua/neogit/status.lua](https://github.com/NeogitOrg/neogit/blob/master/lua/neogit/status.lua) I noticed that stage and discard set `M.current_operation` but unstage does not.
The assertion for unstaging that occasionally fails comes right after an `act()` line, and the last line in `act()` is `status.wait_on_current_operation()`, which checks if `status.current_operation` is set.
I tested locally with just the four unstage tests (the other tests in the status spec were commented), and without this change I ran the test in a loop three times and it failed at runs 122, 119, and 74. With the fix in place, I was not able to reproduce a failure. I ran the test in a loop two times and stopped the loop at runs 1130 and 1360, satisfied that the random …

test: fix random test fail in status spec

---

lua/neogit/status.lua
tests/specs/neogit/popups/branch_spec.lua
tests/specs/neogit/popups/ignore_spec.lua
tests/specs/neogit/popups/log_spec.lua
tests/specs/neogit/popups/remote_spec.lua
tests/specs/neogit/status_spec.lua

Seems pretty straightforward but let me know if anything could be improved!
References: #888

test: remove status wait api in favor of generic operations

---

lua/neogit/buffers/commit_view/ui.lua

this pr fixes a crash when opening a commit if some info about the commit are `nil`
```
Parsing commit...                                                                                                                                                                                   
Error executing vim.schedule lua callback: ...ck/packer/start/plenary.nvim/lua/plenary/async/async.lua:18: The coroutine failed with this message: ...acker/start/neogit/lua/neogit/buffers/commit_v
iew/ui.lua:38: attempt to concatenate field 'author_email' (a nil value)                                                                                                                             …
```

fix: do not crash when opening commit if no email or no user

---

lua/neogit/popups/branch/actions.lua

I feel like the most common use case for branch renames is fixing typos. For me (and likely others) DX would be greatly improved if the prompt would come already prefilled with the name of the branch which is being renamed.
To our luck `input.get_user_input` already supports default value as its second parameter, DRY code achieved!

feat: Prefill branch rename prompt with the selected branch name

---

lua/neogit/lib/state.lua

Absolute paths in windows always start with a drive letter which has to be stripped or formatted. As far as I can tell from my testing this makes detecting the platform unnecessary, as the base path and filename don't need further modification, and stripping a drive letter that isn't there is harmless.
This resolves issue https://github.com/NeogitOrg/neogit/issues/469

format drive letter for per_project_settings

---

README.md
lua/neogit/config.lua

Setting to "false" will leave _all_ mappings up to user.

Feat: Add "use_default_keymaps" boolean to user config.

---

lua/neogit/config.lua

This means that if the current window is `> 80 * 2` cells wide, the editor is opened as a vsplit, otherwise it's opened as a split.
To restore the previous behaviour, just set the values to "split"

Breaking: Change Commit/Merge/Rebase/Tag editor default from "split" to "auto"

---

README.md

Latest commit at time of creating pr (being https://github.com/NeogitOrg/neogit/commit/096249f6c7fa4af5cc6e0d41c4ff2fffb351e273) changes kind for popups, but is not documented in the README, thought I'd just fix that myself

Update neogit kind defaults in README.md

---

lua/neogit.lua

This sets the Neogit `cwd` to the git root if left unspecified. This makes Neogit more in line with Magit in its presentation of files.
Some sceenshots below.
As a note, my git root is `~/dots` for the repo I am demonstrating this in and I am opening Neovim in my `dots/.config/neovim/lua` directory.
Before:
After:
Closes #906

refactor: set Neogit `cwd` to git root if `cwd` unspecified

---

lua/neogit/lib/buffer.lua

See the documentation for `vim.wo` -- the previous implementation set a global value instead of local:
```
vim.wo[{winid}]                                                                *vim.wo*
Get or set window-scoped |options| for the window with handle {winid}.
Like `:set`. If [{winid}] is omitted then the current window is used.
Invalid {winid} or key is an error.
Note: this does not access |local-options| (`:setlocal`) instead use: >lua
nvim_get_option_value(OPTION, { scope = 'local', win = winid })
nvim_set_option_value(OPTION, VALUE, { scope = 'local', win = winid }
<
Example: >lua
local winid = vim.api.nvim_get_current_win()
vim.wo[winid].number = true    -- same as vim.wo.number = true
print(vim.wo.foldmarker)
print(vim.wo.quux)             -- error: invalid key
```
Fixes: …

Use opt_local to set window local variables

---

doc/neogit.txt
lua/neogit/buffers/common.lua
lua/neogit/lib/hl.lua

Hi there,
first of all, thanks again for this amazing package! Long time emacs user decided to switch to nvim just because of you ^^
I was trying to configure the look and feel of the log graph view of `neogit` to match more the original color scheme of magit:
However with my config the colors of neogit look rather dull:
I tried to configure the `NeogitGraph*` highlight groups without success. After digging a bit through the code of neogit, I noticed that you use `Macro` and `String` highlight groups for local/remote branch names. Maybe these could reuse the [NeogitBranch & NeogitRemote](https://github.com/NeogitOrg/neogit/blob/master/doc/neogit.txt#L201-L202) highlight groups instead?
I don't have much experience with Lua or highlight groups, so please let me know if there is another …

Graph colors

---

lua/neogit/lib/git/init.lua
lua/neogit/lib/input.lua
tests/mocks/input.lua

Nothing was using this fancy completion thing, and I have no plans to use it.

Clean up input lib

---

lua/neogit/lib/state.lua

fixes remaining issue on https://github.com/NeogitOrg/neogit/issues/469 where errors were occurring when the state folder didn't already exist on windows.

use plenary.path to handle joining the state path

---

Makefile

Without the changes in this PR `make test` fails on my machine like this
```
$ make test
TEST_FILES=$TEST_FILES NEOGIT_LOG_LEVEL=error NEOGIT_LOG_CONSOLE="sync" GIT_CONFIG_GLOBAL=/dev/null GIT_CONFIG_SYSTEM=/dev/null NVIM_APPNAME=neogit-test nvim --headless -S "./tests/init.lua"
Error detected while processing command line..script /home/stefan/repos/neogit/tests/init.lua:
E5113: Error while calling lua chunk: /home/stefan/repos/neogit/tests/init.lua:1: module 'tests.util.util' not found:
...
```

Update Makefile: Set LUA_PATH

---

doc/neogit.txt
lua/neogit/buffers/common.lua
lua/neogit/lib/hl.lua

Follow-up after #934: In the log graph it's a bit non-intuitive where the currently checked out branch is. To make this more customizable for the user, we could reuse the `NeogitPopupBranchName` highlight group.

Show HEAD as `NeogitPopupBranchName` in Log Graph

---

lua/neogit/buffers/common.lua
lua/neogit/lib/git/log.lua
tests/specs/neogit/lib/git/log_spec.lua

Currently if a commit contains a tag, the tag will be rendered in the log graph with the `NeogitBranch` highlight group. Worse, though, it can happen, that the tag will be misinterpreted as the remote name:
| Before | After |
|:--|:--|
|![graph-tags-before](https://github.com/NeogitOrg/neogit/assets/31999281/fabcfada-0a32-4586-94a0-e0dd217f3ecb)|![graph-tags-after](https://github.com/NeogitOrg/neogit/assets/31999281/285e9b9d-d3c2-42b3-b1cf-c101102469f0)|
The `commit.ref_name` might also contain a tag name, which the log graph is currently rendering in the `NeogitBranch` highlight group. The refname of HEAD with a tag placed on it might look like this:
> HEAD -> main, tag: 1.0.0, origin/main, origin/HEAD
A refname of a tag not associated to any branch might look like this:
> tag: 1.0.0 …

Correct tag highlight in Log Graph

---

lua/neogit.lua
lua/neogit/integrations/diffview.lua
lua/neogit/lib/fs.lua
lua/neogit/lib/git/cli.lua
lua/neogit/lib/git/config.lua
lua/neogit/lib/git/index.lua
lua/neogit/lib/git/init.lua
lua/neogit/lib/git/merge.lua
lua/neogit/lib/git/rebase.lua
lua/neogit/lib/git/repository.lua
lua/neogit/lib/git/sequencer.lua
lua/neogit/lib/git/status.lua
lua/neogit/popups/ignore/actions.lua
lua/neogit/popups/init.lua
lua/neogit/process.lua
lua/neogit/status.lua
tests/README.md
tests/specs/neogit/lib/git/cli_spec.lua
tests/specs/neogit/popups/branch_spec.lua
tests/specs/neogit/popups/remote_spec.lua

This pull request fixes #931 and fixes #442 by ensuring the independence of nearly all library functions from the current working directory (cwd).
Specifically, this pertains to functions that directly or indirectly use cwd, which can change anytime, either manually by the user or automatically through plugins. Cwd dependent functions make it difficult to reason about the state of Neogit and potentially lead to numerous bugs. Throughout the codebase, you can observe various attempts to circumvent this issue, often involving the tracking of the cwd via `state.cwd`.
Notably, all functions in `neogit.lib.git.cli` are dependent on the cwd, with `require("neogit.lib.git.cli").git_root()` being a noteworthy example.
This pull request aims to eliminate all cwd dependencies by designating …

Remove dependency on cwd

---

lua/neogit/lib/finder.lua
lua/neogit/lib/git/branch.lua
lua/neogit/popups/branch/actions.lua
lua/neogit/popups/branch_config/actions.lua
lua/neogit/popups/fetch/actions.lua
lua/neogit/popups/ignore/actions.lua
lua/neogit/popups/pull/actions.lua
lua/neogit/popups/push/actions.lua
lua/neogit/popups/tag/actions.lua

Consolidate the formatting in builder so all callers just need to pass in text.

Standardize prompt prefixes

---

lua/neogit/buffers/common.lua
lua/neogit/lib/git/log.lua
tests/specs/neogit/lib/git/log_spec.lua

Sorry I just noticed, I introduced a small bug in my previous PR #934, where local checked out branches are not rendered with the `NeogitBranchHead`. With a user config of:
```lua
local blue = "#bae7ff"
local remote = "#b4eeb2"
vim.api.nvim_set_hl(0, "NeogitBranch", { fg = blue, bold = true })
vim.api.nvim_set_hl(0, "NeogitBranchHead", { fg = blue, bold = true, underline = true })
vim.api.nvim_set_hl(0, "NeogitRemote", { fg = remote, italic = true })
```
and a branch called `foo` checked out, this is what happens:
|Before|After|
|:--|:--|
|![before](https://github.com/NeogitOrg/neogit/assets/31999281/268f9c5d-71da-424c-a5f1-520230c04581)|![after](https://github.com/NeogitOrg/neogit/assets/31999281/7268f654-c7cf-4a7b-bb15-644a2f2c6a97)|
This PR should fix this now =)

FIX: Properly render HEAD with `NeogitBranchHead` highlight group

---

lua/neogit/buffers/commit_view/init.lua
lua/neogit/buffers/log_view/init.lua
lua/neogit/buffers/reflog_view/init.lua

Found another couple of missing keybinds =)

Merge + Help Popups in {Commit, Log, Reflog} Views

---

README.md
lua/neogit/client.lua
lua/neogit/lib/git/cherry_pick.lua
lua/neogit/lib/git/merge.lua
lua/neogit/lib/git/rebase.lua
lua/neogit/lib/git/reset.lua
lua/neogit/popups/branch/actions.lua
lua/neogit/popups/tag/actions.lua

This provides a working solution for my problem in #938. Let me explain:
With the current four events the user (me^^) can set up a vim autocmd which closes and reopens the Graph View. Not pretty, but does the job for me. However it's a bit cumbersome to being only limited to update the view on commit, push, pull & fetch. With these additional events the log view also does update on other commands:
This is my user config for auto-updating:
```lua
local group = vim.api.nvim_create_augroup("MyCustomNeogitEvents", { clear = true })
vim.api.nvim_create_autocmd("User", {
pattern = {
"NeogitCherryPick",
"NeogitBranchCheckout",
"NeogitBranchCreated",
"NeogitBranchDelete",
"NeogitBranchReset",
"NeogitBranchRename",
"NeogitRebase",
"NeogitReset",
"NeogitTagCreate",
"NeogitTagDelete", …
```

More `Neogit*` Events

---

lua/neogit/buffers/commit_view/init.lua
lua/neogit/buffers/commit_view/ui.lua
lua/neogit/buffers/common.lua
lua/neogit/lib/buffer.lua
lua/neogit/lib/signs.lua
lua/neogit/lib/ui/component.lua
lua/neogit/lib/ui/init.lua
lua/neogit/status.lua

Fixes a long-standing bug if buffers losing their context highlights when unfocused.
TODO:
- Status buffer loses context highlighting when telescope picker is activated (`b l`). Commit view doesn't.
- Status buffer might not render a diff with highlights the first time.

Use line-highlight instead of signs for most things

---

lua/neogit/buffers/commit_view/init.lua
lua/neogit/buffers/commit_view/ui.lua
lua/neogit/buffers/log_view/init.lua
lua/neogit/popups/log/actions.lua
lua/neogit/status.lua

When you filter by filename in the log view, this filter should be applied to the commit buffer if it's opened, and only show diffs for those files.
Closes #1014

Enhancement: Only show filtered file diffs from log view

---

lua/neogit/buffers/commit_editor/init.lua

Fixes #439 
Current issue repro in a neogit status buffer:
- <kbd>ca</kbd> in the status buffer to amend to the last commit.
- Change something in the commit message - don't save the buffer.
- <kbd>q</kbd> to close, a confirmation dialog starts. Hit <kbd>n</kbd>o in the saves changes confirmation dialog to not confirm the changes.
- The commit is made anyway / See the commit sha changing.
Ref.: https://github.com/NeogitOrg/neogit/pull/441#issuecomment-1858869791
With the changes in the PR the commit is not being made when not confirming the changes.
The changes are based on the `abort` implementation:
https://github.com/NeogitOrg/neogit/blob/a6a7ec026bd66fd196565a06bc6353b01327d09a/lua/neogit/buffers/commit_editor/init.lua#L97-L102

Fix close abort

---

lua/neogit/buffers/rebase_editor/init.lua

Hey there !
The rebase editor actions stopped working recently and I was about to open an issue but the fix was really straightforward so I figured it would be even quicker to open a pull request.
In the rebase editor, there is a check trying to match a commit SHA of length 10 instead of 8. Looking at other parts of the code base it doesn't look intentional.
This was preventing most rebase editor actions from modifying the current line, at least on my repository.
Thanks for the awesome plugin by the way, I started using it recently and that's a really nice workflow !

Fixed commit SHA check preventing line actions in rebase editor

---

lua/neogit/status.lua

exist anymore. Just fail quietly, no big deal

Safe call this: when collapsing via `1`, the restore position might not

---

lua/neogit/status.lua

When there's no buffer, it'll crash things.
Fixes #1064

When closing the tab/buffer, this might still fire.

---

lua/neogit/lib/git/cli.lua
lua/neogit/lib/git/status.lua
tests/specs/neogit/status_spec.lua
tests/util/git_harness.lua

Change git status to use `-z` in cli. This will prevent git from escaping unicode characters in path names, so we can properly display characters from all (hopefully) alphabets.
Fixes #1071

Improve unicode support for filepaths.

---

.github/workflows/lint.yml

The `taiki-e/install-action` action pulls the target binary and resorts to building from source if not found. However, Selene is compatible with `cargo-binsall`, eliminating the need for source building.
The `Swatinem/rust-cache` action inherently caches `~/.cargo` directories, including the location where Selene is stored.

Use the Selene binary instead of building from source

---

.github/workflows/lint.yml
.typos.toml
Makefile
doc/neogit.txt

We have identified numerous typos in the past. Hopefully, incorporating `typos` into our linter tools will assist us in minimizing such errors.

Add `typos` linter

---

doc/neogit.txt
lua/neogit/buffers/editor/init.lua
lua/neogit/config.lua
lua/neogit/lib/buffer.lua
lua/neogit/lib/git/log.lua
lua/neogit/lib/util.lua

Adds `NextMessage`, `PrevMessage`, and `ResetMessage` commands to editor buffer. Probably only works nicely for commit messages. Will dig up messages from reflog
todo: docs

Add Next/Previous message to editor

---

lua/neogit/lib/git/branch.lua
lua/neogit/lib/git/cli.lua

Make sure this doesn't show up in cmd history - it's ok to fail, that just means the thing doesn't exist

Hide rev-parse --verify from history

---

README.md

Thanks for adding the Dotfyle badge to the repo! Noticed that the dotfyle badge had a different style, so changed it. This styling aligns with the other badges in the Readme.

Use for-the-badge style for Dotfyle badge

---

lua/neogit/buffers/common.lua
lua/neogit/lib/json.lua
tests/specs/neogit/lib/json_spec.lua

Turns out `vim.json.encode` doesn't produce a deterministic ordering across sessions. Add a final `"null"` field so our escape function will be able to pattern match properly
Fixes #1107

Fix: Json parsing

---

lua/neogit/lib/git/status.lua

@smatting removed dependencies on `cwd` with commit b21711f91b6c86f8d694200a87bca854ea31827c.
This commit removes one missing `cwd` usage.

Fix missing cwd removal

---

lua/neogit/lib/git/rebase.lua
lua/neogit/popups/commit/actions.lua

Use technique from https://peterevans.dev/posts/how-to-rewrite-git-commit-messages-non-interactively/

Allow instantly rebasing what would otherwise require the editor

---

lua/neogit/lib/git/stash.lua
tests/specs/neogit/popups/stash_spec.lua

Sorry just noticed a little bug, with the `stash rename`: When input is `nil` (e.g. when user quit the message prompt with ESC) then the stash is dropped =S

FIX: Proper quiting of `stash rename`

---

lua/neogit/lib/git/status.lua

Closes #1157.
Tested with the example from https://github.com/NeogitOrg/neogit/issues/1157#issuecomment-1926767545:
```lua
-- NEW!
local match_2 = "(.)(.) (....) (%d+) (%d+) (%d+) (%w+) (%w+) (%a%d+) (.+)%z(.+)" 
local rest = "R. N... 100644 100644 100644 ac01e6941fe11104afee78fa73ad77f9707d169b ac01e6941fe11104afee78fa73ad77f9707d169b R100 lua/plugins/lsp/rust-analyzer.lua\0lua/plugins/lsp/rust_analyzer.lua"
local mode_staged, mode_unstaged, _, _, _, _, _, _, _, name, orig_name = rest:match(match_2)
print(orig_name) -- lua/plugins/lsp/rust_analyzer.lua
print(name)      -- lua/plugins/lsp/rust-analyzer.lua
```

Fix string pattern for type-2 `git status -z` entries

---

lua/neogit/lib/git/status.lua
lua/neogit/lib/util.lua
tests/specs/neogit/status_spec.lua

Fix: Rebuild lines that have been "split" incorrectly when a \0 character has been replaced by a \n. This fixes renamed files not being listed properly in the status buffer.
Successor to: https://github.com/NeogitOrg/neogit/pull/1165

Fix: Renamed files not appearing properly in status buffer

---

lua/neogit/lib/graph.lua

This PR fixes a scenario where UTF-8 codepoints passed to gsub would be swapped out with their Unicode replacement.

 Fix: graph invalid UTF-8 codepoint

---

lua/neogit/integrations/diffview.lua

call_sync method trims output by default. DiffView needs to read file as it is.
issue:'Diff view shows a lot of noise caused by blank lines #1108'

Fixed unwanted trim for file from diffview

---

lua/neogit/lib/finder.lua

When choosing a directory with the default telescope sorter, do not select ".." if it's highlighted while there's something else written in the prompt.
This still respects if the user types "..", since thats used instead of the selection.
closes #1180

Bugfix: default telescope sorter with directory picker

---

lua/neogit/config.lua

I ran into this typo in the type annotations while changing my config. (Alternatively, if the string is supposed to be "float", a change elsewhere in the code needs to be made.)

fix: typo in the kind type

---

lua/neogit/lib/finder.lua

This PR includes three commits, explained here.
The default value of the `prompt_prefix` is an indicator `" > "`:
https://github.com/NeogitOrg/neogit/blob/0d0879b0045fb213c328126969a3317c0963d34a/lua/neogit/lib/finder.lua#L152
But whenever the `Finder` was created, it added an indicator as a postfix also:
https://github.com/NeogitOrg/neogit/blob/0d0879b0045fb213c328126969a3317c0963d34a/lua/neogit/lib/finder.lua#L182
So the default value of `prompt_prefix` for users will be `" > > "`, I change the default value to a more meaningful value in this commit.
The behavior of adding a postfix for every `prompt_prefix` has problems too. Because neogit do it whenever the `Finder` is created:
https://github.com/NeogitOrg/neogit/blob/0d0879b0045fb213c328126969a3317c0963d34a/lua/neogit/lib/finder.lua#L …

Various fix for finder's prompt

---

lua/neogit/lib/git/cli.lua
lua/neogit/lib/git/index.lua
lua/neogit/process.lua
lua/neogit/status.lua
tests/specs/neogit/status_spec.lua

Hi @CKolkey, me again (=
AFAIK so far there is no option to discard files which are in conflict. I really liked the Magit way of handling this, that is asking the user to use "ours" or "theirs", so I recreated that behavior in Neogit. 
[Neogit-discard-conflict.webm](https://github.com/NeogitOrg/neogit/assets/31999281/d26bd443-6562-40a7-be28-9ac5b9435d48)
1. This does not work yet rebased on master, because of #1176. Best is not to merge before this is fixed
2. This does only for for entire files up to now. Discarding conflicted hunks does not work. I want to try this next, but have to understand the "patching" logic for hunks. Ideas/explanations welcome

Discard Conflicted Files

---

lua/neogit/lib/git/remote.lua
lua/neogit/popups/branch/actions.lua

In my case, in addition to the default git_services, I use a hosted
Gitlab that uses some ssh tunneling to reach the destination using a
port other than standard. Using the parsing as is results in parsing the
owner as `<port>/actual/owner`. For example ssh://gitlab.priv:2222/priv/group/repo.git
yields owner `2222/priv/group` which constructs a bad url with
configuration `["gitlab.priv"] = "https://gitlab.priv/${owner}/${repository}/-/merge_requests/new?merge_request[source_branch]=${branch_name}&merge_request[target_branch]=main"`.
This probably generally works, because most users of ssh remotes will
either use the git scheme or the default port 22, without specifying.
This patch introduces a more robust git url parsing library function, with support for more url schemes. It also …

Improve parsing of url's in all cases, but specifically for ssh cases.

---

lua/neogit/lib/git/remote.lua
tests/specs/neogit/lib/git/remote_spec.lua

988b2869 introduced a regression where special characters prevented making complete matches. This changes those match patterns to all non-slash characters rather than word characters.
<details>
<summary>Verification output</summary>
```bash
{
host = "github.com",
owner = "owner-with-dash",
proto = "git",
repo = "repo",
repository = "repo",
url = "git@github.com:owner-with-dash/repo.git",
user = "git"
}
{
host = "github.com",
owner = "owner",
proto = "git",
repo = "repo-with-dash",
repository = "repo-with-dash",
url = "git@github.com:owner/repo-with-dash.git",
user = "git"
}
```
</details>

Fix issue where owner and repo have special characters.

---

lua/neogit/lib/git/log.lua
lua/neogit/lib/git/rebase.lua
lua/neogit/popups/rebase/actions.lua
lua/neogit/popups/rebase/init.lua
tests/specs/neogit/popups/rebase_spec.lua

Based on [this](https://github.com/NeogitOrg/neogit/commit/a5d5cc68dcd844eedc2db5a7c399dbec6ef1d49d) we can now also drop a commit.
I suggest to change the keybinding for dropping to "d" since it's unused in that view and feels more natural.

Rebase drop a commit

---

lua/neogit/lib/git/status.lua

The bug was that in a repo which has both a conflict and a renamed file `git status -z --porcelain=2 -b` will report:
```sh
2 R. N... 100644 100644 100644 cd4e4e1ada23361e9ad886a5723bda3aa9419ea8 cd4e4e1ada23361e9ad886a5723bda3aa9419ea8 R100 c.txt
a.txt
u UU N... 100644 100644 100644 100644 15b4f7fdbd22faf05ee23ec5c3a98c775657fe18 7513f79749fe4a5c1942b1f89de63c128a0fedcd d5a2e9b772aa39468c69670ad9bd319bbf197a86 b.txt
```
and that does not match the pattern in:
`    if line:match("^[12u]%s[MTADRCU%s%.%?!][MTDRCU%s%.%?!]%s") or line:match("^[%?!#]%s") then`
so it falls through to the else which appends the unmatched line to the previous line.
The else statement is there to handle renamed files which end up on separate lines so I changed the for loop from a simple one-by-one loop to a loop …

Fix status when files have conflicts

---

lua/neogit/lib/git/status.lua
lua/neogit/status.lua

Hi,
first time PR, small one.
This fixes: #1222
I had a fix for  #1176, but then realized that was solved today , already :)  
So, I took the learning experience to fix another: #1222
During a merge conflict, when the mode is UA: unmerged, added by them, the case was missing and not displaying in the status buffer. Also used #1189, to use discard (keybind x)  to choose between ours/theirs version, which was not available for UA or AU cases. 
Hope it helps, :)

Fix: merge conflict missing files: added by them

---

lua/neogit/buffers/commit_view/init.lua
lua/neogit/buffers/log_view/init.lua

When viewing the commit log, pressing `;` or `,` can be used to open the commit view without focusing it. If you press `;` again, it will scroll down the commit view. With `,` you can scroll up. Because the commit view window isn't focused, you can quickly focus the next commit with `j` or the previous with `k`.
This reduces the amount of key presses significantly when reviewing changes of multiple commits because you don't have to switch windows twice for every commit you want to look at.
Since `f` and `t` are bound differently to normal vim usage, `;` and `,` are also basically free to use. On the US layout (and others), you only need the right hand to review the changes and can use the left hand to drink coffee or tee. ;-)
These bindings implement the same functionality as …

Use ; and , to scroll commit view inside log view

---

lua/neogit/buffers/common.lua
lua/neogit/buffers/status/init.lua
lua/neogit/buffers/status/ui.lua
lua/neogit/lib/popup/ui.lua

This fixes the issues with `<Tab>` in blank spaces. The problem is that the `EmptyLine` component was actually an *instance* of a component, and that instance was being shared between all the sections in the status buffer. That means that when the component tree is rendered, that single instance gets added to `RendererIndex.index` multiple times, and its `position.row_start` field gets overwritten multiple times. This results in the `RendererIndex:find_by_line(line)` method returning a component with a `position.row_start` that is not equal to the `line` argument, and that breaks everything.
I've also fixed an error that pops up if the upstream or pushRemote branches don't have any commits, and made the Head line show `(detached)` again when detached. When detached, the commit hash will …

Status buffer fixes

---

lua/neogit/lib/git/remote.lua
tests/specs/neogit/lib/git/remote_spec.lua

Per the Git Book (https://git-scm.com/book/en/v2/Git-on-the-Server-The-Protocols), `git@remote:repo.git` is a shorthand for `ssh://git@remote/repo.git`. This handles this by explicitly parsing as ssh://... in the `git.remote.parse(url)` funciton.
Closes #1266

Handle git@server:repo.git as a shorthand for ssh://git@server/repo.git in git.remote.parse(url)

---

lua/neogit/buffers/rebase_editor/init.lua
lua/neogit/config.lua
lua/neogit/lib/buffer.lua
lua/neogit/status.lua

The original source code only has one optional value for `disable_line_numbers`. This value initially controls both regular line numbers and relative line numbers if toggled `true/false`. 
I have added an additional config value of the name `disable_relative_line_numbers` with its default value set to `false` which will only control the relatively line number option. 
Each value can then be used independently to give the end-user's more flexibility.

Added config value for relative line numbers

---

lua/neogit/process.lua

Instead of concatenating it's passing the inspected object as a second parameter.
That's throwing an error when files are staged or branches switched from outside Neogit.

Fix error params in process.lua

---

README.md

Updates the default config to include the suppression of the stdout message.
https://github.com/NeogitOrg/neogit/blob/d51199a3552571a02b6d3d88b95acc4102ef2fd2/lua/neogit/config.lua#L222

docs: update readme set verify_commit to default

---

lua/neogit.lua
lua/neogit/lib/git/cli.lua
lua/neogit/lib/git/status.lua

Multiple fixes for issues are contained in this PR:
- This PR fixes Issue #954 by changing:
- the call to `vim.fn.system()` with `plenary.job`, and then testing the return value after the job finishes.
- the call to `git_root_of_cwd()` with `plenary.job`, testing the return value and if in error defaults to `vim.fn.getcwd()` otherwise returns the directory from `git rev-parse --show-toplevel`
On Windows, the `vim.fn.system()` was returning 127, instead of the expected 0, resulting in `false` whenever `is_inside_worktree()` is invoked. In turn, this always means the prompt for initializing the git repos is displayed for every Neogit operation. Plenary.job produces a 0 on success.
Similarly, the call to `git_root_of_cwd()` kept returning the empty string "" (due to the non-zero success …

Use plenary.job to fix .git detection on windows, add regex fix for renamed files 

---

lua/neogit/lib/git/cli.lua

This PR fixes the bug in Issue #1140.
The problem stems from the default directory being returned instead of the detected `.git`'s parent directory. This issue existed prior to PR #1281, but is now properly fixed in this PR.
Specifically, the text of plenary.job's `job_output` is in a table element retrieved by calling `result()` against the table.
With this PR the proper directory top-level is returned wherever `cwd` is defined, including sub-directories, and it also fixes the behavior with `cwd=%:p:h` so that opening files in the subdirectory returns the correct path and one can still open files above the defined `cwd` from within Neogit.

Fix the ability to open a files from within neogit when cwd is set to a subdirectory or external location, fixes Issue #1140

---

lua/neogit/buffers/editor/init.lua
lua/neogit/buffers/rebase_editor/init.lua

Add ZZ and ZQ mappings to editor buffers to properly handle when a user closes the buffer this way. ZZ should commit the change, while ZQ should abort.
Fixes #1296

Editor mappings for `ZZ` and `ZQ`

---

README.md

The README has the incorrect default option for `commit_editor`. The code shows that the default way of opening the default editor is in a new tab.

Fix incorrect default option for commit_editor

---

lua/neogit/buffers/commit_view/ui.lua

In commit view diff deletion highlighting wasn't working due to a typo
The correct highlight name defined in `lua/neogit/lib/hl.lua` is `NeogitDiffDeletions`

Fix typo in highlight name

---

README.md
doc/neogit.txt
lua/neogit/config.lua
lua/neogit/lib/buffer.lua

When I used *Neogit* a few days ago, the diff view was always on the left and the commit message editor on the right. This appears to have switched places.
This adds a `vsplit_left` option to open a new window to the left. In the case of the diff view, this can be set in `opts.commit_editor.staged_diff_split_kind` to open the diff view to the left. This restores the previous behavior.

feat: add `vsplit_left`

---

lua/neogit/lib/buffer.lua

Use `sbuffer` instead of `tabnew` to prevent creating extra `noname`

---

lua/neogit/buffers/commit_view/init.lua

Space is super common to use as leader, so this was shadowing very important keymaps.

Remove unused keybind

---

lua/neogit/lib/git/rebase.lua

the OID instead of failing to display anything

When merging a remote branch with rebase, and a conflict occurs, show

---

CONTRIBUTING.md
Makefile
tests/util/util.lua

A couple of minor tweaks:
- I couldn't get `logger.fmt_debug` to work - strangely it didn't error but it didn't seem to log anything either. I updated `CONTRIBUTING.md` to match how the rest of the code did it.
- The tests were giving me an error as I'm on macos, but have GNU mktemp installed (there are at least 5 of us! 😆) - this detects GNU mktemp via `--version` rather than based on OS.

Contributor tweaks

---

doc/neogit.txt

I was having difficulties getting GPG integration to work on my system as explained in #1245. The issue ended up being that my GPG conf files were placed in the incorrect directory so the config wasn't being picked up. I thought I should add the command I used to work out what directory I needed to use in a note within the docs to help people who may come across this issue in the future.

Updated GPG integration docs

---

lua/neogit/lib/git/cli.lua
lua/neogit/lib/git/config.lua
lua/neogit/lib/git/log.lua
lua/neogit/lib/git/status.lua
lua/neogit/lib/util.lua
lua/neogit/process.lua

Some shells seem to add more than others? It's unclear why, but it causes issues for some people.
The reason it was removed is because it is a bit slow with large input.
https://github.com/NeogitOrg/neogit/issues/1389

Handle removing ANSI escape codes. 

---

lua/neogit/popups/help/actions.lua

Currently the help pop up is broken because keymaps can be equal to `"<nop>"`. This correctly verifies that the keymap is a table before adding it so that it skips `nop`s.
Even with a completely base, minimal installation, running `?` doesn't work at all. This fixes that

fix(help): correctly handle if `keymap` is `"<nop>"`

---

lua/neogit/buffers/process/init.lua
lua/neogit/lib/buffer.lua

As a heads up, I'm unsure if there are issues open (or opened previously) that related to this. I, at least, couldn't find any.
Copied from the body of the commit:
> Problem: Currently `normal ex` commands don't work in terminal mode in Neovim. Currently the `ProcessBuffer` in Neogit displays long running git commands by default in a terminal buffer and sets the cursor to the bottom of the buffer on refresh via `normal G` which causes an error.
> 
> See https://github.com/neovim/neovim/issues/4895 which is the tracking issue in Neovim for `normal ex` commands in terminal mode.
> 
> Solution: Use Neovim's API to explicitly set the cursor position within the `ProcessBuffer`, avoiding invoking an `normal ex` 
Using the following `pre-commit` git hook:
```bash
local count=0
while :; do …
```

fix: do not use `normal ex` cmd for process refresh

---

lua/neogit.lua
lua/neogit/lib/buffer.lua
lua/neogit/lib/ui/init.lua
spec/buffers/log_buffer_spec.rb

The current `Ui:update` function only restores the cursor, but not the "scroll", i.e. the top line, as noted in https://github.com/NeogitOrg/neogit/issues/841#issuecomment-2237724913.
This PR addresses that issue by first restoring the proper top line, taking `scrolloff` and folds into account, then finally restoring cursor. This prevents jumping when folding in the status view.
Here's a video demonstrating before and after:
https://github.com/user-attachments/assets/cefb50a2-107c-4718-a419-417fe1b19aa0
(I'm jumping around a bit in the after one with C-D and C-U, but rest assured the folding restores the scroll like it should)
Now, an alternative to this solution would be to look into a way to update the Ui _without resetting cursor position_ completely. That could perhaps be done by …

Fix restoring scroll when unfolding in status view

---

lua/neogit/buffers/process/init.lua
lua/neogit/process.lua

When loading very very large diffs, appending to the output buffer would perform way way way too much string allocations/rehashing.
To address this, we can stop appending output to this buffer after 300 lines. It may be worth pursuing not appending anything to this buffer at all unless it's a PTY process, but that can be looked into later.

Address performance regression

---

lua/neogit/lib/buffer.lua
lua/neogit/lib/util.lua

This PR fixes a regression introduced by e69c1b01b4cf0803cad5d7e49430af16760be55c, which wraps the closing by `schedule_wrap`. However, by wrapping it, `pcall` will never catch the error by `nvim_win_close`, causing a regression.
Adds a utility to safely close the window, since multiple places called `nvim_win_close` without handling the potential failure.
Fixes #1423.
One concern is the possibility that `nvim_buf_delete` in `Buffer:hide` could cause a similar error, but might be premature to add safety to this.

Fix regression when closing last window

---

lua/neogit/lib/util.lua

Hey!
I've noticed that if a throttled function fails it's considered to be running and any subsequent calls would be cancelled. This PR fixes that by running the target function in protected mode.

Handle target function exceptions in throttle_by_id

---

lua/neogit/popups/push/actions.lua

This is to address #1456 This doesn't entirely fix the issue, but at least it informs about what's wrong:
```
git push origin master:
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
Press ENTER or type command to continue
Error executing vim.schedule lua callback: vim/_editor.lua:0: nvim_exec2(): Vim(buffer):E86: Buffer 9 does not exist
[C]: in function 'nvim_exec2'
vim/_editor.lua: in function 'cmd'
...ln/.local/share/nvim/lazy/neogit/lua/neogit/lib/util.lua:602: in function ''
vim/_editor.lua: in function <vim/_editor.lua:0>
Press ENTER or type command to continue
```

Add message about missing access rights

---

lua/neogit/lib/buffer.lua

The show method was not working correctly for existing windows, while for buffers that are not already visible it would actually make sure to show the buffer by creating the layout according to the `kind` value. Fixes: https://github.com/NeogitOrg/neogit/issues/1373

Fix: actually show/focus buffers when existing window

---

lua/neogit/lib/rpc.lua

When nvim is started with `nvim --listen 127.0.0.1:9999`, rpc connections don't work because `vim.fn.sockconnect` is always called with `pipe` mode.
We can examine the server address and use `tcp` mode if the address looks like `servername:port`.
fixes #383

fix(#383): Make RPC work with tcp servers

---

lua/neogit/lib/git/cli.lua

Allows interaction with the YubiKey PIN prompt. This will allow users to use their passkeys with PINs for Git operations.

Add support for YubiKey "Enter PIN for"

---

README.md
doc/neogit.txt
lua/neogit/config.lua
lua/neogit/popups/branch/actions.lua
tests/specs/neogit/config_spec.lua

This config feature allows users to specify an initial branch name that will be used as a `get_user_input` default when Neogit asks for a name for a new branch.
This is useful when working in teams with a branch naming convention. For example, teams may choose to prefix branches with a GitHub username. In that case, configuring Neogit with:
```
initial_branch_name = "myname/"
```
...will result in the popup being prepopulated with `myname/`, after which I can specify the branch name.

Add config feature 'initial_branch_name'

---

lua/neogit/popups/branch/actions.lua

It was working for rename and spin-off, but not for create. Probably a bad merge.

Fix 'initial_branch_name' on create_branch

---

lua/neogit/config.lua

While configuring this plugin, my LSP kept saying the kind I chose was an error because it was not in the `WindowKind` alias
This PR adds types to the WindowKind alias
referenced: https://github.com/NeogitOrg/neogit/blob/master/lua/neogit.lua#L231
and the [usage part of the readme](https://github.com/NeogitOrg/neogit/tree/master?tab=readme-ov-file#usage) that states which kinds are valid.

fix: windowkind types

---

lua/neogit/lib/ui/init.lua

I got this locally. I'm not sure how I got there, but there I was:
```
...share/nvim/lazy/plenary.nvim/lua/plenary/async/async.lua:18: The coroutine failed with this message: ....local/share/nvim/lazy/neogit/lua/neogit/lib/ui/init.lua:507: attempt to perform arithmetic on field 'hunk _offset' (a nil value)
^I[C]: in function 'error'
^I...share/nvim/lazy/plenary.nvim/lua/plenary/async/async.lua:18: in function 'callback_or_next'
^I...share/nvim/lazy/plenary.nvim/lua/plenary/async/async.lua:45: in function 'step'
^I...share/nvim/lazy/plenary.nvim/lua/plenary/async/async.lua:48: in function 'execute'
^I...share/nvim/lazy/plenary.nvim/lua/plenary/async/async.lua:118: in function 'callback'
^I...share/nvim/lazy/plenary.nvim/lua/plenary/async/async.lua:25: in function …
```

Fix trying to perform arithmetic on nil hunk_offset

---

lua/neogit/lib/popup/builder.lua
lua/neogit/lib/popup/init.lua

Both of the `incompatible` and `dependant` concepts are only implemented for switches, not options. However, options can be incompatible or dependent on each other and switches as well.
Handle both concepts between all options and switches. Use the existing `toggle_switch`/`set_option` to do the disabling so that any recursive dependencies are resolved as well.

Handle `incompatible`/`dependant` for options

---

lua/neogit/lib/git/worktree.lua

When generating a list of worktrees using the 'git worktree list --porcelain' command, a bare worktree only has 2 lines, whereas all other worktrees have 3 lines. Since we don't need to switch to the bare repo, we can safely ignore it. The new listing function will look for a branch listing and only add that to the list of worktrees. 
```
worktree /tmp/ws-nvim/.repos/neogit.git
bare
worktree /tmp/ws-nvim/neogit-bare-worktree-listing-error
HEAD 2b770465b79dfe60898983ddfc897cdf08cf9d34
branch refs/heads/fix-bare-worktree-listing-error
worktree /tmp/ws-nvim/neogit-master
HEAD bae3412ea9ac31292e14e9090dde7cb118cd52c1
branch refs/heads/master
```

fix: process.lua error when we have a bare repo in the worktree list

---

doc/neogit.txt
lua/neogit/lib/popup/builder.lua
lua/neogit/lib/popup/init.lua

As noted in https://github.com/NeogitOrg/neogit/discussions/1542, it could be very useful to use Neogit as a platform for building popups and actions for custom subcommands. Clean up some of the documentation around the builder APIs and mention in the docs the possibility of creating custom commands.

Clean up annotations on APIs that can be made public and document the ability to create custom popups

---

lua/neogit/spinner.lua

Hi @CKolkey, I've been enjoying neogit for a while, and was pleasantly surprised when I saw the spinner messages on most git operation. Thank you!
However, I've run into a small conflict with the spinner steps. Using `echom` pushes the messages into the message history, which means that if the git operation is long enough, we'll pollute the history with redundant messages.
For some context, those messages are useful to explore the output of different processes, specially when a plugin throws an error.
You can explore the history using the built-in `:messages` command, or you can use something like `:Message` from vim-scriptease which sends the message history into the quickfix window.
In this case, I ran an amend on this commit and took a few seconds to reword the message, that sent 93 …

Make spinner step messages transient

---

lua/neogit/lib/git/worktree.lua

Ensure the main worktree, which contains a .git directory, is not deleted by filtering it out from the list of worktrees. Mark any worktree with a .git directory as the main worktree to protect it from deletion.

fix: prevent deletion of the main worktree

---

lua/neogit/lib/buffer.lua

buffer
Fixes: https://github.com/NeogitOrg/neogit/issues/1540

fix: when non-tab buffer has a header, ensure it's closed with the

---

doc/neogit.txt
lua/neogit/config.lua
lua/neogit/process.lua
tests/specs/neogit/config_spec.lua

This pairs very well with the new spinner feature: https://github.com/NeogitOrg/neogit/pull/1551
Allows users to set:
```lua
{ auto_show_console_on = "error" }
```
Note that this is only considered if `auto_show_console` is `true` (this is the default).
This results in Neogit showing a spinner while, e.g. pre-commit hooks are running, and only shows the console if the pre-commit hooks fail.
The default is `auto_show_console_on = "output"`, which matches the previous behavior.
This PR also stops Neogit from calling `notification.warn` on a bad exit code, because this overlaps with showing the console, and requires the user to press enter unnecessarily in order to get to the console output. The `notification.warn` call is preserved if `auto_show_console` is `false`.

feat: Add auto_show_console_on = "output" | "error" setting

---

README.md
doc/neogit.txt

In #1572 I've accidentally added a `["L"] = "StageLine"` keymap that does not exist in upstream `HEAD`. It is a feature that I'm working on locally. Sorry for the noise.

Remove non-existent `StageLine` keymap from documentation

---

lua/neogit/popups/log/actions.lua

When in detached HEAD, the log view crashes because there is no current branch.
This fixes the issue by checking if `git.branch.current()` is `nil` and if it is, creates a custom message "(detached) <subject>".

Handle detached head in log popup

---

lua/neogit/buffers/commit_view/init.lua

Before this addition of the `M:close()` call, it was necessary to press the key for `"OpenOrScrollUp"/"OpenOrScrollDown"` twice to view a different commit. The first key press closed the old commit view and the second opened the current.

Open commit view immediately when switching commits

---

lua/neogit.lua
lua/neogit/buffers/status/actions.lua
lua/neogit/buffers/status/init.lua
lua/neogit/integrations/diffview.lua
lua/neogit/lib/git/bisect.lua
lua/neogit/lib/git/branch.lua
lua/neogit/lib/git/cli.lua
lua/neogit/lib/git/hooks.lua
lua/neogit/lib/git/index.lua
lua/neogit/lib/git/merge.lua
lua/neogit/lib/git/rebase.lua
lua/neogit/lib/git/refs.lua
lua/neogit/lib/git/repository.lua
lua/neogit/lib/git/sequencer.lua
lua/neogit/lib/git/status.lua
lua/neogit/popups/ignore/actions.lua
lua/neogit/popups/worktree/actions.lua
lua/neogit/vendor/types.lua
lua/neogit/watcher.lua
tests/specs/neogit/lib/git/cli_spec.lua
tests/specs/neogit/lib/git/repository_spec.lua

fixes: https://github.com/NeogitOrg/neogit/issues/1474
fixes: https://github.com/NeogitOrg/neogit/issues/1455

Improve worktree support

---

README.md
doc/neogit.txt
lua/neogit/buffers/commit_view/init.lua
lua/neogit/buffers/common.lua
lua/neogit/buffers/reflog_view/ui.lua
lua/neogit/buffers/stash_list_view/ui.lua
lua/neogit/config.lua
lua/neogit/lib/git/log.lua
lua/neogit/lib/git/reflog.lua
lua/neogit/lib/git/stash.lua

This adds the options:
- `commit_date_format`: Applied to the commit view.
- `log_date_format`: Applied to all the dates in a log like view. This includes the log, reflog, stashes.
Closes #1568.

Add custom date format options

---

lua/neogit/popups/commit/actions.lua

This fixes neogit hanging forever when using git absorb as reported in the issue #1564
Closes #1564

fix: git-absorb getting stuck

---

lua/neogit/popups/log/actions.lua

Another set of parentheses is needed.

Fix "Handle detached head in log popup"

---

lua/neogit/buffers/commit_view/init.lua

Discovered this issue while working on custom pager support.

fix(commit-view): fix jump to file, when filenames contain `-`

---

README.md
lua/neogit/config.lua

issues with blinking cursors for users.

Change: config.process_spinner is now `false` by default. 

---

lua/neogit/lib/buffer.lua

Without this check, it could be that `ufo.setup()` is not called before `ufo.detach()`, (for example if UFO is lazy-loaded with `lazy.nvim` which breaks UFO's internal assumptions, and causes an error.
Example of error:
```
Error executing Lua callback: .../share/nvim/lazy/lazy.nvim/lua/lazy/core/handler/cmd.lua:48: Vim:Error executing Lua callback: ...gilice/.local/share/nvim/lazy/nvim-ufo/lua/ufo/bufmanager.lua:111: attempt to index field 'bufDetachSet' (a nil value)
...gilice/.local/share/nvim/lazy/nvim-ufo/lua/ufo/bufmanager.lua:111: in function 'detach'
/home/gilice/.local/share/nvim/lazy/nvim-ufo/lua/ufo/main.lua:174: in function 'detach'
/home/gilice/.local/share/nvim/lazy/nvim-ufo/lua/ufo.lua:99: in function 'detach' …
```

Only try to detach UFO if it is loaded

---

lua/neogit/integrations/diffview.lua

https://github.com/NeogitOrg/neogit/issues/1645 shows that 3 way (also 4 way) diff is no longer opened with diff worktree (`dw` shortcut).
With [a recent change](https://github.com/NeogitOrg/neogit/commit/3f098789c6baaf24c81eb6428444d9fa6364353a) opening diff worktree was changed to use `get_local_diff_view`, as the section_name is now set to "worktree".
But I think the old behaviour of using `dv_lib.diffview_open` is actually preferred, as that will show the 3 (or 4) way diff view for conflicts.

fix: show 3 way diff with diff worktree when there are conflicts

---

lua/neogit/popups/pull/actions.lua

Presently, there are no notifications when there are errors when pulling. This commit adds them.
I'm not sure how you want those to look like, so I've added what feel like sensible defaults. Please feel free to change those.

Error notifications when pulling

---

README.md
doc/neogit.txt
lua/neogit/config.lua
lua/neogit/popups/push/actions.lua

Solves #1673.
A quick and simple addition, but I think I changed everything needed. Tested ok. Default `true`, no surprises. People who dislike it can find the option on their own. Though, I'll be honest, this still feels like a bit of a weird feature to have enabled by default. Spooked me a little.
If there's anything you'd like changed, be it code, names, or even the commit message, feel free to say so. Not sure I got the coding style, so I'm a little scared of introducing stuff that doesn't fit in.

Add prompt_force_push option

---

CONTRIBUTING.md
lua/neogit/lib/git/branch.lua

The current use of `unpack` and `vim.split` to extract the branch name of an upstream ref fails to properly handle branch names containing forward slash (`/`) symbols. In particular, it discards the branch name's portion including and following the first occurrence of a `/` symbol.
For example:
* `pushRemote.ref == "origin/branch/name"`
* `pushRemote.branch (expected) == "branch/name"`
* `pushRemote.branch (actual) == "branch"`
UI example:
This PR replaces this usage of `unpack` and `vim.split` with a regex match that properly handles branch names containing `/` symbols.

fix: pushRemote.branch string extraction

---

lua/neogit/buffers/refs_view/init.lua
lua/neogit/config.lua
lua/neogit/lib/git/branch.lua
lua/neogit/lib/ui/init.lua

Hi there! A small QoL improvement for the refs view from magit. I suspect I may have missed an edge case or two, but it is still pretty handy for bulk-deletion when you have lots of old branches hanging round.
- Allows deleting a branch from the refs view more easily with a direct bind ('x' by default), similar to magit.
- Allows deleting multiple branches simultaneously with a visual selection which makes cleaning up lots of branches much simpler.
I wasn't entirely sure if making a new sub-section `refs_view` in the mappings was the ideal option as it didn't exist already and most of the other mappings it uses open other popups, but that's what I went for - happy to amend if it makes sense to do it a different way.
https://github.com/user-attachments/assets/4cf88f33-ed28-4507-b911-11f6484 …

Refs view: branch deletion

---

lua/neogit/buffers/status/actions.lua

When attempting to open a newly tracked folder in the status window an `Empty buffer` error is raised:
```
Error executing vim.schedule lua callback: vim/_editor.lua:0: nvim_exec2(): Vim(print):E749: Empty buffer
[C]: in function 'nvim_exec2'
vim/_editor.lua: in function 'cmd'
...e/nvim/lazy/neogit/lua/neogit/buffers/status/actions.lua:83: in function ''
vim/_editor.lua: in function <vim/_editor.lua:0>
```
After manually clearing the above error the folder gets opened in whatever file explorer you are using (I'm using Oil.nvim, netrw doesn't seem to have this problem)
I debugged the issue and found that the use of `redraw! | norm! zz` is causing this issue. This might be because of the way Oil creates its file explorer buffer. 
To fix this issue I updated the code to just …

fix: empty buffer error on open buffer action

---

README.md

This plugin initialize in `plugin/` directory, so users don't have to call `setup()` function

README: no require users to call `require 'neogit'.setup()`

---

lua/neogit/lib/buffer.lua

This is only noticeable when a user sets `vim.o.winborder` to a custom value. Without the border option explicitly provided, the header will inherit the border style from the global winborder option, overlapping some first lines in the log view.
Screenshots with `vim.o.winborder = "rounded"`:
* current settings:
* after this PR (will be back to the expected behavior):

fix: set border=none for header text explicitly

---

lua/neogit/client.lua

On MinGW `vim.uv.os_uname().sysname` returns something with `MINGW`. Instead use Luas formatting option [`%q` to correctly escape any character](https://www.lua.org/manual/5.1/manual.html#pdf-string.format).

fix: `\` is not correctly escaped on MinGW

---

README.md
doc/neogit.txt
lua/neogit/config.lua
lua/neogit/lib/buffer.lua

This change allow users to custom floating window like #685, so we can configure it as:
```lua
floating = {
width = 0.5, -- percentage
height = 30, -- row
border = "single",
...
}
```

Allow custom floating window style

---

lua/neogit.lua

Ensure that repo state is populated prior to running an action. Some actions depend on state to not raise an error.

fixes #1714

---

doc/neogit.txt

```sh
cd path/to/neogit
nvim --headless +'helptag doc' +q
```
```
Error in command line:
E154: Duplicate tag "neogit_worktree_checkout" in file doc/neogit.txt
E154: Duplicate tag "neogit_worktree_create_branch" in file doc/neogit.txt⏎
```

Fix duplicated helptags error

---

README.md
doc/neogit.txt
lua/neogit/config.lua
lua/neogit/lib/finder.lua

I was looking for a convenient way to copy branch names and found #1520. However, the proposed solution does not allow copying other branch names than the current one or commit hashes.
I would love a shortcut that allows copying the selection from any finder.

Add command to copy finder selection

---

lua/neogit/popups/diff/actions.lua

This PR addresses two focus-related issues encountered when using the 'Diff for range' functionality:
1.  **Popup Focus:** When selecting a range in the diff view, the first "Diff for range from>" prompt would work correctly, but the subsequent "Diff for range to>" prompt would not be focused.
2.  **Diffview Tab Focus:** After successfully entering both ranges and opening the diff in Diffview, focus would immediately switch back to the Neogit status tab, leaving the Diffview tab open but in the background.
**Solution:**
Both issues were resolved by setting `refocus_status = false` in the `FuzzyFinderBuffer:open_async` calls.
-   Adding `refocus_status = false` to the prompt for "Diff for range from>" fixed the focus issue for the subsequent "Diff for range to>" prompt.
-   Adding …

Fix: Focus issues in 'Diff for range' and Diffview integration

---

lua/neogit/config.lua

This is a quick and small fix to expose the `CloseFold` action in status mappings. This enables config such as: 
```lua
-- ...
mappings = {
status = {
[">"] = "OpenFold",
["<"] = "CloseFold",
}
}
-- ...
```

fix: enable `CloseFold` command in status mappings

---

lua/neogit/lib/git/log.lua

Currently, when performing `reword` on a commit that has whitespace-separated lines, `Neogit` undesirably trims the message.
This behavior is quite bothering, especially if a user uses `--signoff` option.
For example, a commit with a message:
```Gitcommit
fix: disable commit message trimming on `reword`
Signed-off-by: Andrew Chmutov <achmutov@proton.me>
```
is trimmed to
```git
fix: disable commit message trimming on `reword`
Signed-off-by: Andrew Chmutov <achmutov@proton.me>
```
when `reword`'ing.
The suggested changes preserve the whitespace.

fix: disable commit message trimming on `reword`

---

lua/neogit/popups/reset/actions.lua
lua/neogit/popups/reset/init.lua

Reset popup -> branch expects commit under cursor to be in `commits` rather than the in `commit` like the other reset actions.
To reproduce:
1. `:Neogit`
2. place cursor over recent commit
3. open reset popup with `X`
4. select branch option with `b`
expected:
commit under cursor is in picker
actual:
commit is not in picker

fix(popups/reset): branch expects commits

---

lua/neogit/lib/finder.lua

This brings the behaviour in line with the Telescope picker: https://github.com/NeogitOrg/neogit/blob/d6112de97160a09c767e2b9dfba45e8942cbd5a4/lua/neogit/lib/finder.lua#L56
I noticed this trying to do a soft reset with HEAD^1 as the argument, as someone else was asking about here: https://github.com/NeogitOrg/neogit/discussions/1669

Pass through the search prompt if there were no matches when using Snacks picker.

---

lua/neogit/lib/git/rebase.lua
lua/neogit/popups/rebase/actions.lua

Similar to the interactive rebase case, the parent of the selected commit needs to be used so that the selected commit is in the range of commits being rebased.
Fixes: https://github.com/NeogitOrg/neogit/issues/1812

Use parent commit for rebase.subset.

---

README.md

Thanks for the Neogit plugin.
The `git_services` section in the README is incorrectly indented and it's missing a closing brace, so here's a fix.

docs: fix formatting and syntax of git_services
