- README.md
I took a lot of liberty here, but I believe this is a promising project and as such the README should also match this potential.
A **work-in-progress** Magit clone for Neovim that is geared towards the Vim philosophy.*
> Changed the wording of README, added installation steps, and  surrounded keybinds in a table. 

- lua/neogit/lib/util.lua
- lua/neogit/status.lua
- plugin/neogit.vim
This allows 0 or 1 arguments to `:Neogit`, so `:Neogit` retains default behaviour but `:Neogit floating` now uses a floating window
> Add cmd arguments

- .github/workflows/lint.yml
- .github/workflows/test.yml
- .gitignore
- .luacheckrc
- Makefile
- lua/neogit/lib/buffer.lua
- lua/neogit/lib/fs.lua
- lua/neogit/lib/git/branch.lua
- lua/neogit/lib/git/cli.lua
- lua/neogit/lib/git/diff.lua
- lua/neogit/lib/git/status.lua
- lua/neogit/lib/md5.lua
- lua/neogit/lib/notification.lua
- lua/neogit/lib/util.lua
- lua/neogit/popups/commit.lua
- lua/neogit/popups/help.lua
- lua/neogit/status.lua
- tests/mocks/input.lua
- tests/status_buf_spec.lua
Thanks for this nice plugin! I was browsing a bit through the source code to see how it's working and I saw a few warnings.
I thought a style CI would be nice so I largely copied it from nvim-treesitter. The tests are failing at the moment (also on my local machine). This is why I activated `continue-on-error` for this step for now.
The style options are always very opinionated so you should review them on whether you agree on the policies (and changes) or not.
> Add luacheck CI

- lua/neogit/integrations/diffview.lua
- lua/neogit/lib/git/cli.lua
Hello again!
I'm updating the diffview API as I'm [currently implementing the listing and diffing of staged changes](https://github.com/sindrets/diffview.nvim/pull/29). These are the changes needed to be made in order for it to work with the new API.
@TimUntersberger just let me know when you're ready to merge this so that we can time the merging of both these PRs such that we minimize potential complications related to the update.
> chore(diffview): Update the diffview integration.

- lua/neogit/integrations/diffview.lua
Hello again! 
I'm making some [big changes over in diffview](https://github.com/sindrets/diffview.nvim/pull/59) that are going to cause some breakage. These are some small changes that are needed to be made in order for the integration to continue working after I merge that PR on my end. I'll probably merge that tomorrow, so I just wanted to give you a heads-up @TimUntersberger.
> chore: Update the diffview integration.

- lua/neogit/integrations/diffview.lua
Making some [big changes again](https://github.com/sindrets/diffview.nvim/pull/64) over in diffview.
Really sorry about making two breaking changes in less than a month. But after this there won't be any breaking changes in the foreseeable future. Due to the growing scope of the plugin I saw an immediate need to create some more descriptive namespaces.
I'll wait at least until tomorrow to merge the PR on my end.
> chore: Update diffview integration.

- lua/neogit/status.lua
Magit allows the user perform actions on sections titles which in turn affects all of the section contents. This PR adds support for doing staging/unstaging.
> Add support for staging/unstaging on section title

- README.md
- lua/neogit/lib/buffer.lua
Addresses #230 
`:Neogit kind=replace` opens NeogitStatus in the current window.
> feat: open neogit in current window

- README.md
- lua/neogit/popups/commit.lua
- lua/neogit/popups/push.lua
> Emit vim events on push and commit

- lua/neogit.lua
- plugin/neogit.vim
This adds command completion to the `:Neogit` command, see the video:
https://user-images.githubusercontent.com/40792180/178110781-3cabe555-b365-4094-8da5-f8f849c94ef3.mp4
> feat: Neogit command completion

- lua/neogit/popups/branch.lua
> fix: adjustments on branch popup

- lua/neogit/buffers/commit_editor/init.lua
- lua/neogit/popups/commit.lua
> fix: Regression making it impossible to cancel commit.

- lua/neogit/popups/push.lua
> don't require remote if git autosetupRemote is set

- lua/neogit/process.lua
> fix: command execution on nixos

- lua/neogit/status.lua
> feat: focus hunk header on hunk fold

- lua/neogit/status.lua
When jumping to file from hunk, cursor will be set to the same text position as it was on the hunk in the status buffer.
> feat: preserve cursor text position when jumping to file from hunk

- lua/neogit/process.lua
> fix(process): remove sending extra codes

- lua/neogit/client.lua
> fix: escape neovim binary

- lua/neogit/lib/buffer.lua
the changes from #404 created problems, when https://github.com/tiagovla/scope.nvim was also used.
Closing a buffer created a new No Name buffer + window. Which screwed the window layout.
The changes address closing the buffer by its underlying window, when available.
Probably it also fixes this:
https://github.com/TimUntersberger/neogit/issues/402
https://github.com/TimUntersberger/neogit/issues/235
I tested it and the behaviour was expected. (I didn't test if this PR solved these issues)
> chore: close buffer by its underlying window, when available

- lua/neogit/lib/state.lua
> Fixed #469

- lua/neogit.lua
- lua/neogit/lib/git/cli.lua
> fix: consider cwd option when checking if invoked inside a git repo or not

- README.md
add docs for installing neogit with lazy.nvim plugin manager.
> docs(plugins): add docs for installing neogit with lazy.nvim

- lua/neogit/lib/finder.lua
- lua/neogit/lib/git.lua
- lua/neogit/lib/git/branch.lua
- lua/neogit/lib/git/cherry_pick.lua
- lua/neogit/lib/git/cli.lua
- lua/neogit/lib/git/config.lua
- lua/neogit/lib/git/diff.lua
- lua/neogit/lib/git/files.lua
- lua/neogit/lib/git/log.lua
- lua/neogit/lib/git/pull.lua
- lua/neogit/lib/git/push.lua
- lua/neogit/lib/git/remote.lua
- lua/neogit/lib/git/repository.lua
- lua/neogit/lib/git/reset.lua
- lua/neogit/lib/git/stash.lua
- lua/neogit/lib/git/status.lua
- lua/neogit/lib/hl.lua
- lua/neogit/lib/popup.lua
- lua/neogit/lib/popup/builder.lua
Ok @ten3roberts , think I got it now.
> Merge Upstream - 7

- lua/neogit.lua
> feat: support expand for `Neogit cwd=`

- doc/tags
> Bugfix: remove duplicate tag

- lua/neogit/lib/git/init.lua
Standardize input confirmation
> Standardize input confirmation in init lib

- ftplugin/NeogitCommitMessage.lua
- ftplugin/NeogitMergeMessage.lua
- ftplugin/NeogitRebaseTodo.lua
> Check if treesitter parsers are installed differently

- doc/neogit.txt
> Fix typo in docs

- lua/neogit/popups/branch_config/actions.lua
From: https://github.com/CKolkey/neogit/pull/44/files
> Use remotes.pushDefault value if set in branch config popup

- lua/neogit/lib/git.lua
- lua/neogit/lib/git/index.lua
- lua/neogit/status.lua
- tests/hunks_spec.lua
On step in the long quest to make the status module smaller. Extracted from https://github.com/CKolkey/neogit/pull/44
> Extract index related functions from status module into git lib for index

- lua/neogit/lib/git/merge.lua
- lua/neogit/lib/git/rebase.lua
- lua/neogit/lib/git/repository.lua
- lua/neogit/lib/git/sequencer.lua
No reason to do the lower level stuff ourselves. That can be left to plenary.path
Extracted from https://github.com/CKolkey/neogit/pull/44/files
> Rewrite sequencer/rebase/merge libs to use some higher-level filesystem

- lua/neogit/lib/util.lua
- lua/neogit/status.lua
> Extract pad_right into util's module

- lua/neogit/lib/notification.lua
- plugin/neogit.lua
Adds command `:NeogitMessages` to view history of notifications
> Add "NeogitMessages" command to show history of neogit messages

- README.md
- lua/neogit/config.lua
- lua/neogit/lib/finder.lua
Update telescope integration to use the nice auto-detection.
> Use auto-detected telescope integration

- lua/neogit/autocmds.lua
- lua/neogit/lib/hl.lua
- lua/neogit/status.lua
> Add hard-coded fallback colors

- tests/util/util.lua
@treatybreaker I had some issues with the test setup running locally on my macbook - made some tweaks. Everything seems to be in good order here, but let me know if these changes broke something for you or @ten3roberts
> fixup: test setup for macos

- lua/neogit/lib/buffer.lua
Resolve #480 by opening the previous buffer.
> fix: Open previous buffer when closing last window

- README.md
Hello! Thanks for making this awesome plugin. I added a short change to make the `Lazy` install a bit more copy-paste. Thanks for your time!
> Provide full installation example for Lazy distro

- lua/neogit/lib/popup.lua
> Add "split_above" to popup kind that will be resized

- lua/neogit/lib/git/branch.lua
- lua/neogit/lib/git/log.lua
- lua/neogit/popups/branch/actions.lua
- tests/specs/neogit/operations_spec.lua
- tests/util/git_harness.lua
- Remove input from `lib/*` layer, move to action
- Extract reflog updating to git lib
> Refactor branch operations - create

- doc/neogit.txt
- Maybe in the future one would prefer to have docs autogenerated with [the README](https://github.com/kdheepak/panvimdoc), source code documentation, custom scripts, etc for easier maintenance.
- I don't love the name "popups" but it's not that significant. 
- #680: I'm truly sorry for my words here yesterday.  I did not mean to sound cruel.
> Intricate hand-crafted documentation for the basic Lua API made with love and appreciation

- doc/neogit.txt
> Update neogit.txt - add console

- README.md
- lua/neogit.lua
- lua/neogit/config.lua
- lua/neogit/popups/help/init.lua
- lua/neogit/popups/init.lua
- plugin/neogit.lua
- tests/specs/neogit/config_spec.lua
This adds config validation for Neogit and tests for the validation (and config).
This also adds a default function for the config, this is to make isolation for the config easier, especially in tests. See the new tests to see how that is being used.
See #629 for some prior discussion on these changes.
> Add Config Validation

- doc/neogit.txt
- lua/neogit/lib/input.lua
- lua/neogit/lib/popup.lua
- lua/neogit/popups/branch/actions.lua
- lua/neogit/popups/branch/init.lua
- lua/neogit/popups/cherry_pick/actions.lua
- lua/neogit/popups/cherry_pick/init.lua
- lua/neogit/popups/init.lua
- lua/neogit/popups/rebase/init.lua
- lua/neogit/popups/revert/actions.lua
Writing docs, realizing some stuff is subtly wrong.
> Update Documentation and other fixes

- doc/neogit.txt
> Fix duplicate tag

- lua/neogit/status.lua
Oversight in commit 7241375be7b0ee5cf490221b9552f1c4ea871d22
> fix: open commit view of unmerged/unpulled section

- lua/neogit/config.lua
> Allow to set kind=replace in the config

- lua/neogit/lib/popup/init.lua
> Ensure buffer is focused before resizing it.

- lua/neogit/status.lua
- syntax/NeogitStatus.vim
I forgot these were in my personal config and not in the repo. Oops!
> Add highlight groups for left-of-filepath words

- lua/neogit/client.lua
- lua/neogit/lib/git/rebase.lua
- lua/neogit/lib/popup/builder.lua
- lua/neogit/lib/popup/init.lua
- lua/neogit/popups/branch/actions.lua
- lua/neogit/popups/cherry_pick/actions.lua
- lua/neogit/popups/fetch/actions.lua
- lua/neogit/popups/merge/actions.lua
- lua/neogit/popups/pull/actions.lua
- lua/neogit/popups/push/actions.lua
- lua/neogit/popups/rebase/actions.lua
- lua/neogit/popups/remote/actions.lua
- lua/neogit/popups/reset/actions.lua
- lua/neogit/popups/revert/actions.lua
- lua/neogit/popups/stash/actions.lua
> Revert "Refactor Actions"

- lua/neogit/client.lua
- lua/neogit/lib/finder.lua
- lua/neogit/lib/git/rebase.lua
- lua/neogit/lib/popup/builder.lua
- lua/neogit/lib/popup/init.lua
- lua/neogit/popups/branch/actions.lua
- lua/neogit/popups/cherry_pick/actions.lua
- lua/neogit/popups/fetch/actions.lua
- lua/neogit/popups/merge/actions.lua
- lua/neogit/popups/pull/actions.lua
- lua/neogit/popups/push/actions.lua
- lua/neogit/popups/rebase/actions.lua
- lua/neogit/popups/remote/actions.lua
- lua/neogit/popups/reset/actions.lua
- lua/neogit/popups/revert/actions.lua
- lua/neogit/popups/stash/actions.lua
> Revert "Revert "Refactor Actions""

- README.md
- lua/neogit/config.lua
- lua/neogit/status.lua
Use this to hide a section.
Fixes #712, #760
> Add section.hidden config value for all status buffer sections. 

- doc/neogit.txt
- lua/neogit/lib/git/status.lua
> Track untracked files in a way that respects status.showUntrackedFiles

- lua/neogit/lib/popup/init.lua
> set nolist for popups

- lua/neogit/lib/hl.lua
> If a HL group is reversed, respect that when getting fg/bg color

- lua/neogit/lib/hl.lua
> Bugfix: Only respect reverse if there is something to consume.

- README.md
- lua/neogit/config.lua
- lua/neogit/lib/git/repository.lua
- lua/neogit/lib/util.lua
- lua/neogit/status.lua
- lua/neogit/watcher.lua
Successor to https://github.com/NeogitOrg/neogit/pull/614
That PR got a bit overcomplex.
> Add basic filewatcher

- lua/neogit.lua
Don't require plugin files until initialized. The idea being to be a better citizen.
> Hide requires in setup function/open function

- lua/neogit/lib/popup/builder.lua
- lua/neogit/lib/popup/init.lua
- lua/neogit/popups/log/init.lua
https://github.com/NeogitOrg/neogit/assets/7228095/8ff97f3a-ead2-4c03-9fd1-1c1827f3ea42
> Implement log commit order selector

- lua/neogit/buffers/commit_view/ui.lua
> Empty table won't work as the alternative - needs to be wrapped in a row()

- lua/neogit/lib/git/diff.lua
- lua/neogit/lib/git/status.lua
> Add ability to build diffs for renamed files

- README.md
- lua/neogit/config.lua
- lua/neogit/lib/buffer.lua
- lua/neogit/status.lua
- tests/specs/neogit/config_spec.lua
See https://github.com/NeogitOrg/neogit/discussions/820#discussioncomment-6982271
> Add config option to disable/enable line numbers in the status buffer

- lua/neogit/popups/log/actions.lua
- tests/specs/neogit/popups/log_spec.lua
References: #824
Feedback very welcome, I will try to take a look at a fix soon but wanted to start with a failing test case.
> test: default switch persistence with remember_settings

- lua/neogit/buffers/common.lua
- lua/neogit/popups/log/init.lua
Don't show decorated ref names when not asked for.
Closes #830
> Respect log view --decorate flag

- tests/specs/neogit/popups/log_spec.lua
References: #830 
Also touches up a couple minor things I noticed with the previous test I wrote. Let me know if you have any other suggestions!
> test: coverage for log decorate switch

- README.md
> docs: remove notification config from readme

- tests/specs/neogit/popups/log_spec.lua
Also updated to reset switches before each test and close the log popup after each test.
The "respects decorate switch" test assertion has been updated since graph is on by default, and the switches are now being reset before each test.
I should also mention I tried using `tests.mocks.input` instead of the `<C-u>` and such, but it didn’t seem to work, from what I could tell it was not clearing the existing value (default of 256 in this case).
> test: coverage for log limiting

- lua/neogit/config.lua
> temp: Disable filewatcher until double-render bug is addressed

- tests/specs/neogit/popups/log_spec.lua
Trace line evolution not included, possibly buggy.
> test: more tests for log limiting

- README.md
- doc/neogit.txt
- lua/neogit/config.lua
- lua/neogit/lib/util.lua
- lua/neogit/popups/branch/actions.lua
- lua/neogit/popups/branch/init.lua
https://github.com/NeogitOrg/neogit/issues/118#issuecomment-1732557767
`b o` to open the pull request URL for branches with an upstream configured.
> Branch Popup: Pull Request action

- Makefile
- lua/neogit/lib/git/log.lua
- tests/init.lua
- tests/specs/neogit/lib/git/log_spec.lua
Fixes #866 
I had no idea you could add a commit without a message. Wild.
> Handle when a git commit has no message

- lua/neogit/lib/finder.lua
> Bugfix: Log filter by file

- lua/neogit/config.lua
- lua/neogit/lib/git/status.lua
- lua/neogit/popups/ignore/actions.lua
- lua/neogit/popups/ignore/init.lua
- lua/neogit/popups/init.lua
- lua/neogit/status.lua
- tests/specs/neogit/popups/ignore_spec.lua
- tests/util/git_harness.lua
- ~~[ ] Ignore extension using glob~~
> Add ignore popup

- lua/neogit/client.lua
Split this out so users can apply different config to it.
> Use tag editor

- lua/neogit/popups/push/actions.lua
- lua/neogit/popups/push/init.lua
Implemented command to push all tags.
> Implemented push tags action

- lua/neogit/popups/log/init.lua
Instead of https://github.com/NeogitOrg/neogit/pull/894
> Add --reflog to log popup

- lua/neogit/lib/git/index.lua
- lua/neogit/status.lua
- tests/specs/neogit/lib/git/index_spec.lua
> fix: git apply denies paths outside the current working directory

- lua/neogit/lib/git/status.lua
> Show "Both Modified" files in unstaged changes, and add absolute_path

- lua/neogit/popups/branch/actions.lua
Fixes https://github.com/NeogitOrg/neogit/issues/915
> fix open pull request with many path segments in URL

- .luarc.json
- lua/neogit/popups/branch/actions.lua
> Add notification after renaming, include current branch in list of local

- lua/neogit/buffers/commit_view/init.lua
- lua/neogit/buffers/log_view/init.lua
- lua/neogit/buffers/reflog_view/init.lua
- lua/neogit/config.lua
- lua/neogit/lib/buffer.lua
- lua/neogit/popups/help/actions.lua
- lua/neogit/popups/init.lua
- lua/neogit/popups/tag/actions.lua
- lua/neogit/popups/tag/init.lua
> Add back TagPopup mapping, other fixes

- lua/neogit/buffers/description_editor.lua
- lua/neogit/client.lua
- lua/neogit/config.lua
- lua/neogit/editor.lua
- lua/neogit/lib/git/cli.lua
- lua/neogit/lib/git/config.lua
- lua/neogit/popups/branch/init.lua
- lua/neogit/popups/branch_config/actions.lua
Fixes #933
Also, implements a proper multi-line description editor
> Fix: rewrite how we parse config values so we can handle multi-line

- doc/neogit.txt
- lua/neogit.lua
https://github.com/NeogitOrg/neogit/issues/864
Credit to @b0o
@ten3roberts How do you feel about this?
> Add experimental API for accessing popup actions directly.

- lua/neogit/process.lua
Fixes https://github.com/NeogitOrg/neogit/issues/965
> Fix bug: non-zero processes cause crashes

- lua/neogit/buffers/commit_view/init.lua
- lua/neogit/buffers/log_view/init.lua
- lua/neogit/buffers/reflog_view/init.lua
Same story as in https://github.com/NeogitOrg/neogit/pull/972 =)
> CHANGE: Allow to open fetch popup from commit, log, reflog views

- README.md
- lua/neogit/buffers/commit_view/init.lua
- lua/neogit/buffers/common.lua
- lua/neogit/config.lua
- lua/neogit/lib/ansi.lua
- lua/neogit/lib/git/log.lua
- lua/neogit/lib/git/status.lua
- lua/neogit/lib/graph.lua
- lua/neogit/lib/ui/component.lua
- lua/neogit/popups/log/actions.lua
- lua/neogit/popups/log/init.lua
set config `graph_style = "unicode"` for unicode graphs.
Not in color, yet.
> Flog graph

- lua/neogit/status.lua
> Check both status and popup maps for hints

- lua/neogit/lib/git/cli.lua
> Fix on_error when opening in a non-git directory

- lua/neogit.lua
- lua/neogit/lib/util.lua
> Add support for internal args to .action() api

- lua/neogit/lib/git/repository.lua
> Call scheduler first so the cli call doesn't crash when invoked via

- lua/neogit/lib/git/cli.lua
- lua/neogit/lib/git/log.lua
- lua/neogit/lib/git/rebase.lua
- lua/neogit/lib/git/remote.lua
- lua/neogit/popups/rebase/actions.lua
> Improve rebase interactive

- doc/neogit.txt
- lua/neogit/buffers/commit_view/init.lua
- lua/neogit/buffers/rebase_editor/init.lua
- lua/neogit/lib/buffer.lua
Adds linewise actions for the rebase todo buffer.
> Enhance rebase interactive actions

- lua/neogit/lib/git/branch.lua
- lua/neogit/lib/git/cli.lua
- lua/neogit/lib/git/fetch.lua
> When fetching after checkout, repo state isn't updated. Need to check

- lua/neogit/popups/branch/actions.lua
between tags/branches with same name.
#971
> Allow resetting to tags, and use full ref names to prevent collision

- lua/neogit/popups/branch/actions.lua
> Fix: Can't prefix heads/, remotes/, tags/ and expect things to work

- lua/neogit/buffers/commit_editor/init.lua
- lua/neogit/buffers/rebase_editor/init.lua
- lua/neogit/client.lua
- lua/neogit/config.lua
- lua/neogit/lib/buffer.lua
- lua/neogit/lib/git/rebase.lua
- lua/neogit/lib/util.lua
> Expand on Rebase Buffer commands

- lua/neogit/buffers/commit_editor/init.lua
- lua/neogit/buffers/rebase_editor/init.lua
- lua/neogit/config.lua
> Fix help popup mappings

- lua/neogit/buffers/rebase_editor/init.lua
> fix: Hashes can be 7 chars long

- lua/neogit/lib/util.lua
- lua/neogit/popups/branch/actions.lua
... as the first options, if they exist
> When resetting a branch, offer that branch's upstream and pushRemote

- lua/neogit/integrations/diffview.lua
> No need to strip blank lines anymore - this is now the default behaviour

- lua/neogit/config.lua
- lua/neogit/integrations/diffview.lua
- lua/neogit/lib/popup/init.lua
- lua/neogit/popups/diff/actions.lua
- lua/neogit/popups/diff/init.lua
- lua/neogit/popups/init.lua
- lua/neogit/status.lua
Breaking! Remove status command "diff at file", and remap diff popup to `d`
Fixes #1034
> Diff Popup Enhancements

- lua/neogit/lib/popup/init.lua
> Remove leading space in popup menus

- lua/neogit/lib/buffer.lua
- lua/neogit/status.lua
> Remove frame-key from decoration provider

- lua/neogit/lib/git/branch.lua
- lua/neogit/lib/git/log.lua
- lua/neogit/lib/git/pull.lua
- lua/neogit/lib/git/push.lua
- lua/neogit/lib/git/remote.lua
- lua/neogit/lib/git/rev_parse.lua
- lua/neogit/lib/git/status.lua
- lua/neogit/lib/util.lua
Looks like we were doing some extra calls.
> Performance - launch time

- lua/neogit/lib/git/branch.lua
- lua/neogit/lib/git/status.lua
- lua/neogit/popups/branch/actions.lua
- lua/neogit/popups/branch_config/actions.lua
- lua/neogit/popups/pull/actions.lua
- lua/neogit/popups/push/actions.lua
- tests/specs/neogit/popups/branch_spec.lua
> Fix: deleting a branch (local) with slash in name.

- .github/workflows/automerge-nightly.yml
- .github/workflows/test.yml
Lets see if this is stupid or not.
> Add automerge action to keep nightly up to date with master

- lua/neogit/lib/git/rebase.lua
- lua/neogit/status.lua
> Shorten displayed OID for rebase section items, and allow full OID to be

- lua/neogit/buffers/rebase_editor/init.lua
If the line uses single char command, continue using those.
> Add support for single char rebase commands

- lua/neogit/lib/git/branch.lua
- lua/neogit/popups/branch/actions.lua
- lua/neogit/popups/branch/init.lua
- tests/specs/neogit/popups/branch_spec.lua
and allow creating branches from HEAD, and other HEADs
Fixes #1113
> Refactor branch checkout and creation

- lua/neogit/lib/git/branch.lua
- lua/neogit/popups/rebase/actions.lua
- lua/neogit/popups/rebase/init.lua
> Extract base_branch() function into git.branch module

- lua/neogit/buffers/commit_view/ui.lua
- lua/neogit/buffers/common.lua
- lua/neogit/lib/hl.lua
I had issues with highlighting on light background and fixed them.
Issue https://github.com/NeogitOrg/neogit/issues/807 describes a similar problem and can IMHO be closed.
> Fix highlighting when showing the commit message

- lua/neogit/lib/git/cli.lua
- lua/neogit/lib/git/rebase.lua
- lua/neogit/popups/rebase/actions.lua
- lua/neogit/popups/rebase/init.lua
- tests/mocks/commit_select_buffer.lua
- tests/specs/neogit/popups/rebase_spec.lua
Implementation based on https://peterevans.dev/posts/how-to-rewrite-git-commit-messages-non-interactively/
Closes #1114
> Rebase to Reword

- lua/neogit/lib/git/status.lua
> Revert "Fix string pattern for type-2 `git status -z` entries"

- lua/neogit/popups/tag/actions.lua
> Do not always annotate tags unless specified.

- lua/neogit/buffers/rebase_editor/init.lua
> Add count support for line_action in reabse todo

- doc/neogit.txt
- lua/neogit/buffers/commit_select_view/init.lua
- lua/neogit/buffers/status/init.lua
- lua/neogit/config.lua
- lua/neogit/lib/buffer.lua
- lua/neogit/lib/git.lua
- lua/neogit/lib/git/cli.lua
- lua/neogit/lib/git/refs.lua
- lua/neogit/lib/hl.lua
- lua/neogit/lib/input.lua
- lua/neogit/popups/bisect/actions.lua
- lua/neogit/popups/bisect/init.lua
- lua/neogit/popups/branch/actions.lua
- lua/neogit/popups/branch_config/actions.lua
- lua/neogit/popups/cherry_pick/actions.lua
- lua/neogit/popups/commit/actions.lua
- lua/neogit/popups/fetch/actions.lua
- lua/neogit/popups/log/actions.lua
- lua/neogit/popups/merge/actions.lua
- lua/neogit/popups/pull/actions.lua
- lua/neogit/popups/push/actions.lua
- lua/neogit/popups/rebase/actions.lua
- lua/neogit/popups/reset/actions.lua
- lua/neogit/popups/reset/init.lua
- lua/neogit/popups/revert/actions.lua
- lua/neogit/popups/worktree/actions.lua
various places - they can now all get refs from refs.
> Feature: Commit select buffer header

- lua/neogit/buffers/editor/init.lua
- lua/neogit/lib/git/cli.lua
- lua/neogit/lib/git/log.lua
- lua/neogit/lib/git/rebase.lua
- lua/neogit/popups/commit/actions.lua
- lua/neogit/popups/rebase/actions.lua
- lua/neogit/popups/revert/actions.lua
- tests/specs/neogit/popups/rebase_spec.lua
Builds on top of @gollth's work in #1118 
todo: 
- Gotta fix the tests now that they don't use the input...
> Update rebase/reword to use full editor experience

- lua/neogit/buffers/editor/init.lua
- lua/neogit/buffers/rebase_editor/init.lua
> Test using lua callbacks for buffer detach

- lua/neogit/status.lua
> Don't crash when discarding untracked files

- README.md
- lua/neogit/buffers/diff/init.lua
- lua/neogit/config.lua
> Allow opening the staged diff in a vsplit

- lua/neogit/buffers/process/init.lua
Alternative to https://github.com/NeogitOrg/neogit/pull/1304
> Add terminal mode mappings for console

- lua/neogit/buffers/status/init.lua
- lua/neogit/lib/buffer.lua
status buffer after long processes, like push and pull
> Add user autocmds so we can listen for our own events and refresh the

- lua/neogit/lib/buffer.lua
Closes https://github.com/NeogitOrg/neogit/issues/1289
> Fix: Don't leave behind no-name buffers

- README.md
- lua/neogit/config.lua
- lua/neogit/process.lua
> Add: config for auto_close_console - close the console if the process

- README.md
- lua/neogit/buffers/status/init.lua
- lua/neogit/config.lua
> Add config for move up and move down in status buffer

- README.md
- lua/neogit/buffers/status/actions.lua
- lua/neogit/buffers/status/init.lua
- lua/neogit/config.lua
Bound to `o` by default.
Todo: Add more configuration for other forges.
Closes #1327
> Feat: Add 'OpenTree' to status buffer. Opens tree in your web browser.

- lua/neogit/buffers/status/init.lua
- lua/neogit/lib/git/merge.lua
- lua/neogit/lib/git/rebase.lua
- lua/neogit/lib/git/repository.lua
Run rebase and merge interactively to handle password input (if required)
> Tweaks for rebase and merge

- lua/neogit/logger.lua
Makes the log output a bit easier to read.
> Add ms information to internal logger

- lua/neogit/lib/ui/init.lua
- lua/neogit/lib/ui/renderer.lua
- spec/buffers/status_buffer_spec.rb
- spec/support/helpers.rb
- spec/support/neovim_client.rb
have interger filenames.
Fixes #1399
> Remove ID index - this is unused, and causes issues with files which

- lua/neogit/buffers/commit_select_view/init.lua
- lua/neogit/buffers/commit_view/init.lua
- lua/neogit/buffers/diff/init.lua
- lua/neogit/buffers/editor/init.lua
- lua/neogit/buffers/log_view/init.lua
- lua/neogit/buffers/rebase_editor/init.lua
- lua/neogit/buffers/reflog_view/init.lua
- lua/neogit/lib/buffer.lua
> Disable setting statuscolumn for all buffers if "disable_signs" is set

- lua/neogit/buffers/status/init.lua
- lua/neogit/config.lua
- lua/neogit/lib/buffer.lua
- spec/buffers/status_buffer_spec.rb
- spec/support/context/nvim.rb
- spec/support/neovim_client.rb
Fixes: #1397
When user sets a mapping to `false`, don't completely crash.
Also fixes when users set up custom functions
> Fix: Mappings (kinda)

- lua/neogit/lib/buffer.lua
> Don't change the viewport if there are fewer lines in the buffer than

- lua/neogit/buffers/status/actions.lua
- lua/neogit/integrations/diffview.lua
- lua/neogit/lib/git/branch.lua
- lua/neogit/lib/git/cherry_pick.lua
- lua/neogit/lib/git/cli.lua
- lua/neogit/lib/git/index.lua
- lua/neogit/lib/git/remote.lua
- lua/neogit/lib/git/reset.lua
- lua/neogit/lib/git/revert.lua
- lua/neogit/lib/git/stash.lua
- lua/neogit/lib/git/status.lua
- lua/neogit/lib/git/tag.lua
- lua/neogit/lib/git/worktree.lua
- lua/neogit/popups/branch/actions.lua
> Rename "async" to "await", and make sure all commands that update repo

- lua/neogit/lib/git/cherry_pick.lua
- lua/neogit/popups/cherry_pick/init.lua
- lua/neogit/popups/merge/init.lua
Not sure why these options were in a `TODO` comment; do we maybe need to keep it as a comment?
> Add cherry-pick options/switches

- lua/neogit/popups/push/actions.lua
Resolves #1188 
This PR introduces a feature that prompts the user to confirm whether they want to force push when their branch has diverged. The feature is based on [lazygit's implementation](https://github.com/jesseduffield/lazygit/blob/8bcfa3660ae17bca0ce7f8c727b1a770fbf88f08/pkg/gui/controllers/sync_controller.go#L208-L227) that provides a similar prompt.
> feat: ask user if to force push when branches diverged

- lua/neogit/lib/rpc.lua
- spec/popups/commit_popup_spec.rb
- spec/support/context/nvim.rb
- spec/support/neovim_client.rb
- Rename field from `ch` to `channel_id`
- add mode field to RPC class
- add spec for connecting and committing via TCP client
- extend neovim client to allow setup/teardown of TCP client
> Small cleanup:

- lua/neogit/lib/git/repository.lua
- tests/specs/neogit/lib/git/repository_spec.lua
> By default use last used dir in Repo.instance 

- doc/neogit.txt
- lua/neogit/buffers/commit_select_view/init.lua
- lua/neogit/buffers/commit_select_view/ui.lua
- lua/neogit/buffers/common.lua
- lua/neogit/buffers/log_view/init.lua
- lua/neogit/buffers/log_view/ui.lua
- lua/neogit/config.lua
- lua/neogit/lib/git/index.lua
- lua/neogit/lib/git/log.lua
- lua/neogit/lib/git/rebase.lua
- lua/neogit/lib/git/reflog.lua
- lua/neogit/lib/git/reset.lua
- lua/neogit/lib/graph.lua
- lua/neogit/lib/graph/kitty.lua
- lua/neogit/lib/graph/unicode.lua
- lua/neogit/popups/cherry_pick/actions.lua
- lua/neogit/popups/commit/actions.lua
- lua/neogit/popups/log/actions.lua
- lua/neogit/popups/log/init.lua
- lua/neogit/popups/rebase/actions.lua
- lua/neogit/popups/revert/actions.lua
> Capture backup of index prior to performing a hard reset.

- README.md
Just thought this would be nice to see in the readme for people that didn't see this option in a Youtube video.
> Added floating kind to values to readme

- lua/neogit/buffers/stash_list_view/init.lua
- lua/neogit/buffers/status/actions.lua
- lua/neogit/config.lua
- lua/neogit/lib/buffer.lua
- lua/neogit/lib/ui/component.lua
- lua/neogit/lib/util.lua
- lua/neogit/popups/log/actions.lua
- lua/neogit/process.lua
- lua/neogit/spinner.lua
> Spinner WIP

- lua/neogit/lib/hl.lua
The self adaping bg color implemetation is great, but that doesn't work for custom color palette has only main colors, so I fetch these custom colors before the bg colors are calculated.
> Self-adaping background color for custom color palette

- lua/neogit/popups/commit/actions.lua
- lua/neogit/popups/remote/actions.lua
changes staged. Thats the whole point...
> Fix: Commit --allow-empty shouldn't return early because you have no

- lua/neogit/lib/finder.lua
Allow multi-selection by default for fzf.
> Allow multi-selection for fzf

- doc/neogit.txt
This is mostly to match the [Configuration section of the README](https://github.com/NeogitOrg/neogit/blob/master/README.md#configuration)
> Update Vim docs for Neogit

- lua/neogit/config.lua
> update NeogitConfigMappingsStatus enum

- lua/neogit/buffers/status/actions.lua
Thought I might try to fix https://github.com/NeogitOrg/neogit/issues/1621 (=
> Fix: Allow `s` to stage resolved files

- lua/neogit/lib/buffer.lua
Pass buffer handle to ensure we do not accidentally set options for buffers we do not intend to.
> fix setting buffer options

- lua/neogit/lib/input.lua
As I use `dressing` to show my inputs where im looking, I wanted to update neogit to use `vim.ui.input` to be able to handle this. As alot of plugins use `vim.ui.input` as a standard.
> reafactor: use `vim.ui.input` instead of `vim.fn.input`

- lua/neogit/lib/finder.lua
Snacks.picker does not call a `close` action by default. This change uses the `on_close` callback instead. ([snacks.nvim/docs/picker.md](https://github.com/folke/snacks.nvim/blob/main/docs/picker.md))
Note: `confirm` is a shortcut to `actions = { confirm = confirm }`
> Fix snacks.picker confirm action and on_close callback

- lefthook.yml
- lua/neogit/popups/branch/actions.lua
- lua/neogit/popups/branch_config/init.lua
- lua/neogit/popups/diff/init.lua
- lua/neogit/popups/fetch/actions.lua
- lua/neogit/popups/pull/actions.lua
- lua/neogit/popups/push/actions.lua
- lua/neogit/popups/remote/actions.lua
- lua/neogit/popups/remote_config/init.lua
- spec/general_spec.rb
- spec/spec_helper.rb
fixes: https://github.com/NeogitOrg/neogit/issues/1751
> Add timeout and specs for launching popup without status buffer

- lua/neogit/integrations/diffview.lua
Code should now correctly put conflicts in the `conflicting` table (and not in the `working` table).
Handles doing a diff on "staged", "unstaged", as well as "diff this" on both of those sections or individual files.
Handles all conflict modes (though I don't know how to ever get UA/AU)
Also now handles opening an unstaged/staged view from the "merge" section.
Fixes #1774
Screenshots of the different cases:
1. worktree diff (baseline, what was already working):
2. Diff this (`dd`) on an unstaged, non-conflict (baseline, was working before):
3. Diff this (`dd`) on an unstaged, conflict:
4. Diff unstaged / diff this (`dd`) on unstaged header:
5. Diff staged / diff this (`dd`) on staged header: 
6. Diff this (`dd`) on merge header (pulled up empty diffview previously):
> fix(diffview): in status, conflicts use merge tool

- lua/neogit/lib/finder.lua
Fix https://github.com/ibhagwan/fzf-lua/issues/2345#issue-3425249624.
> Fix fzf-lua default border config

- doc/neogit.txt
This files was missed when adding the new open commit feature
> docs: update get_services documentation for changes from #1817
